/* Copyright (C) 2016 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/

#ifndef __EVENT_H__
#define __EVENT_H__
#include "cfw_multi_sim.h"
//
// System level Events
//
#define EV_SYS_BASE 0
#define EV_SYS_END_ 50

#define EV_SHL_CFW_STATUS_IND (EV_SYS_BASE + 10)
#define EV_COS_CALLBACK (EV_SYS_BASE + 11)
#define EV_COS_TIMER_CALLBACK (EV_SYS_BASE + 12)
#define EV_COS_CALLBACK_SYNC (EV_SYS_BASE + 13)

//
// DM Events.
//
#define EV_DM_BASE (50)
#define EV_DM_END_ (120)

//
// PM Evetns.
//
#define EV_PM_BASE (120)
#define EV_PM_END_ (150)

#define EV_CFW_START_ (500)

#define EV_CFW_NW_RSP_BASE (500)
#define EV_CFW_NW_RSP_END_ (550)

#define EV_CFW_CC_RSP_BASE (550)
#define EV_CFW_CC_RSP_END_ (600)

#define EV_CFW_SS_RSP_BASE (600)
#define EV_CFW_SS_RSP_END_ (650)

#define EV_CFW_SIM_RSP_BASE (700)
#define EV_CFW_SIM_RSP_END_ (760)

#define EV_CFW_SMS_RSP_BASE (760)
#define EV_CFW_SMS_RSP_END_ (800)

#define EV_CFW_PBK_RSP_BASE (800)
#define EV_CFW_PBK_RSP_END_ (850)

#define EV_CFW_GPRS_RSP_BASE (850)
#define EV_CFW_GPRS_RSP_END_ (900)

#define EV_CFW_FAX_RSP_BASE (900)
#define EV_CFW_FAX_RSP_END_ (950)

#define EV_CFW_TTS_RSP_BASE (950)
#define EV_CFW_TTS_RSP_END_ (970)

#define EV_CFW_TCPIPUDP_RSP_BASE (1000)
#define EV_CFW_TCPIPUDP_RSP_END_ (1050)

#define EV_CFW_HTTP_RSP_BASE (1050)
#define EV_CFW_HTTP_RSP_END_ (1100)

#define EV_CFW_SHELL_RSP_BASE (1100)
#define EV_CFW_SHELL_RSP_END_ (1150)

#define EV_CFW_TM_RSP_BASE (1150) // Test Module
#define EV_CFW_TM_RSP_END_ (1200)

#define EV_RMC_BASE (1200) // Remote Control Module
#define EV_RMC_END_ (1300)

#define EV_CFW_WIFI_RSP_BASE (1300) // Test Module
#define EV_CFW_WIFI_RSP_END_ (1350)
#define EV_WIFI_RSP_BASE (1300)
#ifdef WIFI_SUPPORT
#define EV_WIFI_RSP_END_ (1350)
#define EV_WIFI_IND_BASE (1351)
#define EV_WIFI_IND_END_ (1400)
#endif

#ifdef BT_ENABLE
#define EV_MSG_ID_BT_BASE (1400)
#define EV_MSG_ID_BT_END_ (2100)

#endif

// ...
// 1200 -- 5000 reserved.
//

#define EV_CFW_IND_BASE (5000)
#ifdef LTE_NBIOT_SUPPORT
#define EV_CFW_IND_END_ (5070)
#else
#define EV_CFW_IND_END_ (5050)
#endif

#define EV_CFW_END_ (6000)

//
// AFW event.
//
#define AFW_EV_BASE (7000)
#define AFW_EV_END_ (8000)

//
// UI FW event
//
#define UI_FW_EV_BASE (9000)
#define UI_FW_EV_END_ (10000)

#define CSW_SRV_EV_END_ (0x000FFFFF)

//
// User Event: 0x00100000 -- 0xA0000000
//
#define EV_MMI_EV_BASE 0x00100000
#define EV_MMI_EV_END_ 0xA0000000

// ...
// 0xA0000000 -- 0xF0000000 reserved by system.
//

//
// CSW Private Event 0xF0000001 --  0xF000F000
// used by CSW internal only
//
#define EV_CSW_PRV_BASE 0xF0000001
#define EV_CSW_PRV_END_ 0xF000F000

//
// CSW Private Event 0xF000F001 --  0xFFFFF000
//
#define EV_CSW_REQ_BASE 0xF000F001
#define EV_CSW_REQ_END_ 0xFFFFF000 // don't change this value!

// ...
// 0xFFFFF000 -- 0xFFFFFFF reserved by system.
//

#define EV_EMU_BASE 0xF0000000

//
// Helper Macros
//
#define IS_CFW_EVNET(evId) (((evId) >= EV_CFW_START_) && (evId) < EV_CFW_END_)

//
// DM & TIM Event.
//
#define EV_DM_POWER_ON_IND (EV_DM_BASE + 1)
#define EV_DM_POWER_OFF_IND (EV_DM_BASE + 5)
#define EV_TIM_ALRAM_IND (EV_DM_BASE + 6)
#define EV_DM_UART_RECEIVE_DATA_IND (EV_DM_BASE + 8)
#define EV_DM_EXTI_IND (EV_DM_BASE + 9)
#define EV_DM_GPIO_IND (EV_DM_BASE + 10)
#define EV_DM_RECORD_END_IND (EV_DM_BASE + 11)
#define EV_DM_STREAM_END_IND (EV_DM_BASE + 12)
#define EV_DM_GPADC_IND (EV_DM_BASE + 13)
#define EV_TIM_SET_TIME_IND (EV_DM_BASE + 14)

//guoh add speech indication, if start call, this indication will send to mmi task
#define EV_DM_SPEECH_IND (EV_DM_BASE + 15)

#define EV_DM_AUDIO_OPER_MSG_START (EV_DM_BASE + 16)

#define EV_DM_AUDIO_CONTROL_IND (EV_DM_BASE + 16)
#define EV_DM_SET_AUDIO_VOLUME_IND (EV_DM_BASE + 17)
#define EV_DM_SET_MIC_GAIN_IND (EV_DM_BASE + 18)
#define EV_DM_SET_AUDIO_MODE_IND (EV_DM_BASE + 19)

#define EV_DM_AUD_SETUP_IND (EV_DM_BASE + 20)
#define EV_DM_AUD_STREAM_START_IND (EV_DM_BASE + 21)
#define EV_DM_AUD_STREAM_STOP_IND (EV_DM_BASE + 22)
#define EV_DM_AUD_STREAM_PAUSE_IND (EV_DM_BASE + 23)
#define EV_DM_AUD_STREAM_RECORD_IND (EV_DM_BASE + 24)
#define EV_DM_AUD_TEST_MODE_SETUP_IND (EV_DM_BASE + 25)
#define EV_DM_AUD_FORCE_RECV_MIC_SEL_IND (EV_DM_BASE + 26)
#define EV_DM_AUD_SET_CUR_OUTPUT_DEVICE_IND (EV_DM_BASE + 27)
#define EV_DM_AUD_MUTE_OUTPUT_DEVICE_IND (EV_DM_BASE + 28)
#define EV_DM_AUD_LOUDSPK_WITH_EP_IND (EV_DM_BASE + 29)

#define EV_DM_VOIS_RECORD_START_IND (EV_DM_BASE + 30)
#define EV_DM_VOIS_RECORD_STOP_IND (EV_DM_BASE + 31)

#define EV_DM_ARS_SETUP_IND (EV_DM_BASE + 33)
#define EV_DM_ARS_RECORD_IND (EV_DM_BASE + 34)
#define EV_DM_ARS_PAUSE_IND (EV_DM_BASE + 35)
#define EV_DM_ARS_STOP_IND (EV_DM_BASE + 36)

#define EV_DM_AUDIO_OPER_MSG_END (EV_DM_BASE + 39)

// don't change the following definition
#define EV_KEY_DOWN (EV_DM_BASE + 40)
#define EV_KEY_PRESS (EV_DM_BASE + 41)
#define EV_KEY_UP (EV_DM_BASE + 42)
#define EV_TIMER (EV_DM_BASE + 43)
#define EV_DOUBLE_KEY_DOWN (EV_DM_BASE + 44)
#define EV_DOUBLE_KEY_UP (EV_DM_BASE + 45)
#define EV_DM_UART_MUX_RECEIVE_DATA_IND (EV_DM_BASE + 46)
#define EV_DM_AUD_SET_BT_NREC_FLAG_IND (EV_DM_BASE + 47)
#define EV_DM_READ_UART_DATA_IND (EV_DM_BASE + 48)
#define EV_DM_UART_ATOC_IND (EV_DM_BASE + 49)
#define EV_DM_DTMF_DETECT_IND (EV_DM_BASE + 50)
#define EV_CFW_SPECIAL_DTMF_KEY_IND (EV_DM_BASE + 51)
#define EV_DM_XXX_END (EV_DM_BASE + 52)
#if (EV_DM_XXX_END >= (EV_DM_END_))
#error 'Error: invalid EV_DM_XXX_END definition!'
#endif

//
// PM Event
//
#define EV_PM_BC_IND (EV_PM_BASE + 1)
#define EV_PM_XXX_IND_END (EV_PM_BASE + 2)

#if (EV_PM_XXX_IND_END >= (EV_PM_END_))
#error 'Error: invalid EV_CFW_XXX_IND definition!'
#endif

//
// CFW IND Event.
//
#define EV_CFW_INIT_IND (EV_CFW_IND_BASE + 1)
#define EV_CFW_SRV_STATUS_IND (EV_CFW_IND_BASE + 2)
#define EV_CFW_NW_SIGNAL_QUALITY_IND (EV_CFW_IND_BASE + 3)
#define EV_CFW_NW_REG_STATUS_IND (EV_CFW_IND_BASE + 5)
#define EV_CFW_CC_SPEECH_CALL_IND (EV_CFW_IND_BASE + 6)
#define EV_CFW_CC_CRSSINFO_IND (EV_CFW_IND_BASE + 7)
#define EV_CFW_NEW_SMS_IND (EV_CFW_IND_BASE + 8)
#define EV_CFW_SMS_INFO_IND (EV_CFW_IND_BASE + 9)
#define EV_CFW_CC_CALL_INFO_IND (EV_CFW_IND_BASE + 10)
#define EV_CFW_SIM_STATUS_IND (EV_CFW_IND_BASE + 11)
#define EV_CFW_SS_USSD_IND (EV_CFW_IND_BASE + 12)
#define EV_CFW_CC_RELEASE_CALL_IND (EV_CFW_IND_BASE + 13)
#define EV_CFW_CC_ERROR_IND (EV_CFW_IND_BASE + 14)
#define EV_CFW_SAT_CMDTYPE_IND (EV_CFW_IND_BASE + 15)
#define EV_CFW_PBK_IND (EV_CFW_IND_BASE + 16)
#define EV_CFW_NW_NETWORKINFO_IND (EV_CFW_IND_BASE + 17)
#define EV_CFW_GPRS_CXT_ACTIVE_IND (EV_CFW_IND_BASE + 18)
#define EV_CFW_GPRS_CXT_DEACTIVE_IND (EV_CFW_IND_BASE + 19)
#define EV_CFW_GPRS_MOD_IND (EV_CFW_IND_BASE + 20)
#define EV_CFW_GPRS_STATUS_IND (EV_CFW_IND_BASE + 21)
#define EV_CFW_GPRS_DATA_IND (EV_CFW_IND_BASE + 22)
#define EV_CFW_GPRS_CTRL_RELEASE_IND (EV_CFW_IND_BASE + 23)

#define EV_CFW_TCPIP_BEARER_LOSING_IND (EV_CFW_IND_BASE + 24) // TCP/IP IND
#define EV_CFW_TCPIP_REV_DATA_IND (EV_CFW_IND_BASE + 25) // TCP/IP IND
#define EV_CFW_TCPIP_CLOSE_IND (EV_CFW_IND_BASE + 26)    // TCP/IP close IND
#define EV_CFW_TCPIP_ERR_IND (EV_CFW_IND_BASE + 27)      // TCP/IP ERROR IND
#define EV_CFW_TCPIP_ACCEPT_IND (EV_CFW_IND_BASE + 28)   // TCP/IP accept IND
#define EV_CFW_ICMP_DATA_IND (EV_CFW_IND_BASE + 29)

#define EV_CFW_DNS_RESOLV_SUC_IND (EV_CFW_IND_BASE + 30)
#define EV_CFW_DNS_RESOLV_ERR_IND (EV_CFW_IND_BASE + 31)
#define EV_CFW_PPP_DATA_IND (EV_CFW_IND_BASE + 32)
#define EV_CFW_PPP_TERMINATE_IND (EV_CFW_IND_BASE + 33)

//Frank add used MMS/PUSH
#define EV_CFW_NEW_EMS_IND (EV_CFW_IND_BASE + 35)
#define EV_CFW_ATT_STATUS_IND (EV_CFW_IND_BASE + 36)
#define EV_CFW_CC_STATUS_IND (EV_CFW_IND_BASE + 37)
#define EV_CFW_CC_PROGRESS_IND (EV_CFW_IND_BASE + 38)

#define EV_CFW_CB_MSG_IND (EV_CFW_IND_BASE + 40)
#define EV_CFW_CB_PAGE_IND (EV_CFW_IND_BASE + 41)

#define EV_CFW_BLUETOOTH_DATA_IND (EV_CFW_IND_BASE + 42)
#define EV_CFW_BLUETOOTH_WAKEUP_IND (EV_CFW_IND_BASE + 43)

#ifdef WIFI_SUPPORT
//#define EV_CFW_WIFI_CONNECTED_IND              (EV_CFW_IND_BASE+37)
//#define EV_CFW_WIFI_DATA_IND                   (EV_CFW_IND_BASE+35)
//#define EV_CFW_WIFI_TEST_MODE_DATA_IND (EV_CFW_IND_BASE+36)
#endif

#define EV_CFW_REG_UPDATE_IND (EV_CFW_IND_BASE + 44)

#ifdef __SUPPORT_SMSCLASS__
#define EV_CFW_NEW_SMS_PDU_IND (EV_CFW_IND_BASE + 45)
#endif

#define EV_CFW_EXIT_IND (EV_CFW_IND_BASE + 48)
#ifdef LTE_NBIOT_SUPPORT
#define EV_CFW_ERRC_CONNSTATUS_IND (EV_CFW_IND_BASE+49)
#define EV_CFW_GPRS_PDN_CTX_ACTIVE_IND       (EV_CFW_IND_BASE+51)
#define EV_CFW_GPRS_SEC_CTX_ACTIVE_IND       (EV_CFW_IND_BASE+52)
#define EV_CFW_GPRS_SEC_CTX_DEACTIVE_IND     (EV_CFW_IND_BASE+53)
#define EV_CFW_GPRS_CTX_MODIFY_IND           (EV_CFW_IND_BASE+54)
#define EV_CFW_GPRS_EDRX_IND           (EV_CFW_IND_BASE+55)
#define EV_CFW_GPRS_CCIOTOPT_IND   (EV_CFW_IND_BASE+56)
#define EV_CFW_GPRS_APNCR_IND   (EV_CFW_IND_BASE+57)
#define EV_CFW_GPRS_CRTDCP_IND   (EV_CFW_IND_BASE+58)
#define EV_CFW_GPRS_NONIPDATA_IND   (EV_CFW_IND_BASE+59)
#define EV_CFW_IPERF_REV_DATA_IND                (EV_CFW_IND_BASE+60)
#define EV_CFW_XX_IND_END                        (EV_CFW_IND_BASE+61)
#else
#define EV_CFW_XX_IND_END                        (EV_CFW_IND_BASE+49)
#endif //LTE_NBIOT_SUPPORT

#define EV_CFW_TCPIP_DATA_FR_ACKED_IND   (EV_CFW_IND_BASE+62)

#if (EV_CFW_XX_IND_END >= (EV_CFW_IND_END_))
#error 'Error: invalid EV_CFW_XXX_IND definition!'.
#endif

//
// Emulator Event
//
#define EV_EMU_SCM_REQ (EV_EMU_BASE + 1)
#define EV_EMU_SCL_RSP (EV_EMU_BASE + 2)
#define EV_EMU_SCL_REQ (EV_EMU_BASE + 3)
#define EV_EMU_SCL_TST (EV_EMU_BASE + 4)
#define EV_EMU_TRACE (EV_EMU_BASE + 5)
#define EV_EMU_SYSTEM (EV_EMU_BASE + 6)
#define EV_EMU_EXIT (EV_EMU_BASE + 7)
#define EV_EMU_SCL_AUDIO (EV_EMU_BASE + 10)
#define EV_EMU_LCD (EV_EMU_BASE + 11)
#define EV_EMU_INPUT (EV_EMU_BASE + 12)
#ifdef GPS_SUPPORT
#define EV_GPS_RECV_IND (EV_EMU_BASE + 13)
#endif
//
// NW Response Event.
//
#define EV_CFW_NW_SET_BAND_RSP (EV_CFW_NW_RSP_BASE + 1)
#define EV_CFW_NW_GET_IMEI_RSP (EV_CFW_NW_RSP_BASE + 2)
#define EV_CFW_NW_GET_SIGNAL_QUALITY_RSP (EV_CFW_NW_RSP_BASE + 3)
#define EV_CFW_NW_SET_REGISTRATION_RSP (EV_CFW_NW_RSP_BASE + 4)
#define EV_CFW_NW_DEREGISTER_RSP (EV_CFW_NW_RSP_BASE + 5)
#define EV_CFW_NW_GET_AVAIL_OPERATOR_RSP (EV_CFW_NW_RSP_BASE + 6)
#define EV_CFW_NW_ABORT_LIST_OPERATORS_RSP (EV_CFW_NW_RSP_BASE + 7)
#define EV_CFW_SET_COMM_RSP (EV_CFW_NW_RSP_BASE + 8)
#define EV_CFW_NW_STORELIST_IND (EV_CFW_NW_RSP_BASE + 9)
#define EV_CFW_XCPU_TEST_RSP (EV_CFW_NW_RSP_BASE + 10)
#define EV_CFW_WCPU_TEST_RSP (EV_CFW_NW_RSP_BASE + 11)
#define EV_CFW_NW_GET_QSCANF_RSP (EV_CFW_NW_RSP_BASE + 12)
#define EV_CFW_NW_CELL_LIST_INFO_IND (EV_CFW_NW_RSP_BASE + 13)

//
// GPRS Response Event.
//
#define EV_CFW_GPRS_CTX_MODIFY_ACC_RSP (EV_CFW_GPRS_RSP_BASE + 1)
#define EV_CFW_GPRS_ATT_RSP (EV_CFW_GPRS_RSP_BASE + 2)
#define EV_CFW_GPRS_ACT_RSP (EV_CFW_GPRS_RSP_BASE + 3)
#define EV_CFW_GPRS_CXT_ACTIVE_RSP (EV_CFW_GPRS_RSP_BASE + 4)
#define EV_CFW_GPRS_MOD_RSP (EV_CFW_GPRS_RSP_BASE + 5)
#define EV_CFW_WIFI_CONNECTED_RSP (EV_CFW_GPRS_RSP_BASE + 6)
#define EV_CFW_GPRS_APPSN_RSP (EV_CFW_GPRS_RSP_BASE + 7)
//
// CC Response Event
//
#define EV_CFW_CC_ACCEPT_SPEECH_CALL_RSP (EV_CFW_CC_RSP_BASE + 1)
#define EV_CFW_CC_CALL_HOLD_MULTIPARTY_RSP (EV_CFW_CC_RSP_BASE + 2)
#define EV_CFW_CC_INITIATE_SPEECH_CALL_RSP (EV_CFW_CC_RSP_BASE + 3)
#define EV_CFW_CC_RELEASE_CALL_RSP (EV_CFW_CC_RSP_BASE + 4)
//
//call recorde
//
#define EV_CFW_CALL_REC_REQ (EV_CFW_CC_RSP_BASE + 5)
//
//TTS 
//
#define EV_CFW_TTS_PLAY 	(EV_CFW_TTS_RSP_BASE + 1)
#define EV_CFW_TTS_PAUSE 	(EV_CFW_TTS_RSP_BASE + 2)
#define EV_CFW_TTS_RESUME 	(EV_CFW_TTS_RSP_BASE + 3)
#define EV_CFW_TTS_STOP 	(EV_CFW_TTS_RSP_BASE + 4)

//
// SS Response Event
//
#define EV_CFW_SS_QUERY_CLIP_RSP (EV_CFW_SS_RSP_BASE + 1)
#define EV_CFW_SS_SET_CALL_WAITING_RSP (EV_CFW_SS_RSP_BASE + 2)
#define EV_CFW_SS_QUERY_CALL_WAITING_RSP (EV_CFW_SS_RSP_BASE + 3)
#define EV_CFW_SS_SET_CALL_FORWARDING_RSP (EV_CFW_SS_RSP_BASE + 4)
#define EV_CFW_SS_QUERY_CALL_FORWARDING_RSP (EV_CFW_SS_RSP_BASE + 5)
#define EV_CFW_SS_SET_FACILITY_LOCK_RSP (EV_CFW_SS_RSP_BASE + 6)
#define EV_CFW_SS_GET_FACILITY_LOCK_RSP (EV_CFW_SS_RSP_BASE + 7)
#define EV_CFW_SS_CHANGE_PWD_RSP (EV_CFW_SS_RSP_BASE + 8)
#define EV_CFW_SS_QUERY_FACILITY_LOCK_RSP (EV_CFW_SS_RSP_BASE + 9)
#define EV_CFW_SS_QUERY_CLIR_RSP (EV_CFW_SS_RSP_BASE + 10)
#define EV_CFW_SS_QUERY_COLP_RSP (EV_CFW_SS_RSP_BASE + 11)
#define EV_CFW_SS_SEND_USSD_RSP (EV_CFW_SS_RSP_BASE + 12)
#define EV_CFW_SS_TERMINATE_RSP (EV_CFW_SS_RSP_BASE + 13)
#define EV_CFW_SS_QUERY_COLR_RSP (EV_CFW_SS_RSP_BASE + 14)

//
// SIM Response Event
//
#define EV_CFW_SIM_ADD_PBK_RSP (EV_CFW_SIM_RSP_BASE + 1)
#define EV_CFW_SIM_DELETE_PBK_ENTRY_RSP (EV_CFW_SIM_RSP_BASE + 2)
#define EV_CFW_SIM_GET_PBK_ENTRY_RSP (EV_CFW_SIM_RSP_BASE + 3)
#define EV_CFW_SIM_LIST_PBK_ENTRY_RSP (EV_CFW_SIM_RSP_BASE + 4)
#define EV_CFW_SIM_GET_PBK_STRORAGE_RSP (EV_CFW_SIM_RSP_BASE + 5)
#define EV_CFW_SIM_GET_PBK_STRORAGE_INFO_RSP (EV_CFW_SIM_RSP_BASE + 6)
#define EV_CFW_SIM_GET_PROVIDER_ID_RSP (EV_CFW_SIM_RSP_BASE + 7)
#define EV_CFW_SIM_CHANGE_PWD_RSP (EV_CFW_SIM_RSP_BASE + 8)
#define EV_CFW_SIM_GET_AUTH_STATUS_RSP (EV_CFW_SIM_RSP_BASE + 9)
#define EV_CFW_SIM_ENTER_AUTH_RSP (EV_CFW_SIM_RSP_BASE + 11)
#define EV_CFW_SIM_SET_FACILITY_LOCK_RSP (EV_CFW_SIM_RSP_BASE + 12)
#define EV_CFW_SIM_GET_FACILITY_LOCK_RSP (EV_CFW_SIM_RSP_BASE + 13)
#define EV_CFW_SIM_DELETE_MESSAGE_RSP (EV_CFW_SIM_RSP_BASE + 15)
#define EV_CFW_SIM_WRITE_MESSAGE_RSP (EV_CFW_SIM_RSP_BASE + 16)
#define EV_CFW_SIM_READ_MESSAGE_RSP (EV_CFW_SIM_RSP_BASE + 17)
#define EV_CFW_SIM_LIST_MESSAGE_RSP (EV_CFW_SIM_RSP_BASE + 18)
#define EV_CFW_SIM_GET_SMS_STORAGE_INFO_RSP (EV_CFW_SIM_RSP_BASE + 19)
#define EV_CFW_SIM_READ_BINARY_RSP (EV_CFW_SIM_RSP_BASE + 20)
#define EV_CFW_SIM_UPDATE_BINARY_RSP (EV_CFW_SIM_RSP_BASE + 21)
#define EV_CFW_SIM_GET_SMS_PARAMETERS_RSP (EV_CFW_SIM_RSP_BASE + 22)
#define EV_CFW_SIM_SET_SMS_PARAMETERS_RSP (EV_CFW_SIM_RSP_BASE + 23)
#define EV_CFW_SIM_GET_MR_RSP (EV_CFW_SIM_RSP_BASE + 24)
#define EV_CFW_SIM_SET_MR_RSP (EV_CFW_SIM_RSP_BASE + 25)
#define EV_CFW_SIM_COMPOSE_PDU_RSP (EV_CFW_SIM_RSP_BASE + 26)
#define EV_CFW_SAT_ACTIVATION_RSP (EV_CFW_SIM_RSP_BASE + 27)
#define EV_CFW_SAT_GET_STATUS_RSP (EV_CFW_SIM_RSP_BASE + 28)
#define EV_CFW_SAT_RESPONSE_RSP (EV_CFW_SIM_RSP_BASE + 29)
#define EV_CFW_SAT_GET_INFORMATION_RSP (EV_CFW_SIM_RSP_BASE + 30)
#define EV_CFW_SIM_SET_PREF_OPERATOR_LIST_RSP (EV_CFW_SIM_RSP_BASE + 31)
#define EV_CFW_SIM_GET_PREF_OPERATOR_LIST_RSP (EV_CFW_SIM_RSP_BASE + 32)
#define EV_CFW_SIM_GET_PREF_OPT_LIST_MAXNUM_RSP (EV_CFW_SIM_RSP_BASE + 33)
#define EV_CFW_SIM_SET_PBKMODE_RSP (EV_CFW_SIM_RSP_BASE + 34)
#define EV_CFW_SIM_GET_PBKMODE_RSP (EV_CFW_SIM_RSP_BASE + 35)
#define EV_CFW_SIM_INIT_SMS_RSP (EV_CFW_SIM_RSP_BASE + 36)
#define EV_CFW_SIM_LIST_COUNT_PBK_ENTRY_RSP (EV_CFW_SIM_RSP_BASE + 37)
#define EV_CFW_SIM_RESET_RSP (EV_CFW_SIM_RSP_BASE + 38)
#define EV_CFW_SIM_GET_PUCT_RSP (EV_CFW_SIM_RSP_BASE + 39)
#define EV_CFW_SIM_SET_PUCT_RSP (EV_CFW_SIM_RSP_BASE + 40)
#define EV_CFW_SIM_GET_ACMMAX_RSP (EV_CFW_SIM_RSP_BASE + 41)
#define EV_CFW_SIM_SET_ACMMAX_RSP (EV_CFW_SIM_RSP_BASE + 42)
#define EV_CFW_SIM_SET_ACM_RSP (EV_CFW_SIM_RSP_BASE + 43)
#define EV_CFW_SIM_GET_ACM_RSP (EV_CFW_SIM_RSP_BASE + 44)
#define EV_CFW_SIM_READ_EF_RSP (EV_CFW_SIM_RSP_BASE + 45)
#define EV_CFW_SIM_GET_FILE_STATUS_RSP (EV_CFW_SIM_RSP_BASE + 46)
#define EV_CFW_SIM_READ_RECORD_RSP (EV_CFW_SIM_RSP_BASE + 47)
#define EV_CFW_SIM_UPDATE_RECORD_RSP (EV_CFW_SIM_RSP_BASE + 48)
#define EV_CFW_SIM_GET_SPN_RSP (EV_CFW_SIM_RSP_BASE + 49)
#define EV_CFW_SIM_GET_SMS_TOTAL_NUM_RSP (EV_CFW_SIM_RSP_BASE + 50)
#define EV_CFW_SIM_GET_ICCID_RSP (EV_CFW_SIM_RSP_BASE + 51)
#define EV_CFW_SIM_CLOSE_RSP (EV_CFW_SIM_RSP_BASE + 52)
#define EV_CFW_SIM_SEARCH_PBK_RSP (EV_CFW_SIM_RSP_BASE + 53)
#define EV_CFW_SIM_POWER_OFF_RSP (EV_CFW_SIM_RSP_BASE + 54)
#define EV_CFW_SIM_READ_ELEMENTARY_RSP (EV_CFW_SIM_RSP_BASE + 55)
#define EV_CFW_SIM_GET_EID_RSP  (EV_CFW_SIM_RSP_BASE+56)
//
// SMS Response Event.
//
#define EV_CFW_SMS_DELETE_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 1)
#define EV_CFW_SMS_GET_STORAGE_RSP (EV_CFW_SMS_RSP_BASE + 2)
#define EV_CFW_SMS_SET_STORAGE_RSP (EV_CFW_SMS_RSP_BASE + 3)
#define EV_CFW_SMS_LIST_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 4)
#define EV_CFW_SMS_READ_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 5)
#define EV_CFW_SMS_SEND_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 6)
#define EV_CFW_SMS_SET_CENTER_ADDR_RSP (EV_CFW_SMS_RSP_BASE + 7)
#define EV_CFW_SMS_GET_CENTER_ADDR_RSP (EV_CFW_SMS_RSP_BASE + 8)
#define EV_CFW_SMS_SET_TEXT_MODE_PARAM_RSP (EV_CFW_SMS_RSP_BASE + 9)
#define EV_CFW_SMS_GET_TEXT_MODE_PARAM_RSP (EV_CFW_SMS_RSP_BASE + 10)
#define EV_CFW_SMS_WRITE_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 11)
#define EV_CFW_SMS_LIST_MESSAGE_HRD_RSP (EV_CFW_SMS_RSP_BASE + 12)
#define EV_CFW_SMS_COPY_MESSAGE_RSP (EV_CFW_SMS_RSP_BASE + 13)
#define EV_CFW_SMS_SET_UNREAD2READ_RSP (EV_CFW_SMS_RSP_BASE + 14)
#define EV_CFW_SMS_SET_UNSENT2SENT_RSP (EV_CFW_SMS_RSP_BASE + 15)
#define EV_CFW_SMS_SET_READ2UNREAD_RSP (EV_CFW_SMS_RSP_BASE + 16)
#define EV_CFW_SMS_SET_PARAM_RSP (EV_CFW_SMS_RSP_BASE + 17)
#define EV_CFW_SIM_PATCH_RSP (EV_CFW_SMS_RSP_BASE + 18)
#define EV_CFW_CB_READ_SIM_RSP (EV_CFW_SMS_RSP_BASE + 19)
#define EV_CFW_SMS_MOVE_RSP (EV_CFW_SMS_RSP_BASE + 20)
#define EV_CFW_CB_SET_MID_SIM_RSP (EV_CFW_SMS_RSP_BASE + 21)
#define EV_CFW_SIM_PATCHEX_RSP (EV_CFW_SMS_RSP_BASE + 22)
//
// PBK Response Event
//
#define EV_CFW_PBK_ADD_RSP (EV_CFW_PBK_RSP_BASE + 1)
#define EV_CFW_PBK_UPDATE_ENTRY_RSP (EV_CFW_PBK_RSP_BASE + 2)
#define EV_CFW_PBK_DELETE_RSP (EV_CFW_PBK_RSP_BASE + 3)
#define EV_CFW_PBK_DELETE_BATCH_ENTRIES_RSP (EV_CFW_PBK_RSP_BASE + 4)
#define EV_CFW_PBK_FIND_ENTRY_RSP (EV_CFW_PBK_RSP_BASE + 5)
#define EV_CFW_PBK_LIST_ENTRIES_RSP (EV_CFW_PBK_RSP_BASE + 6)
#define EV_CFW_PBK_GET_ENTRY_RSP (EV_CFW_PBK_RSP_BASE + 7)
#define EV_CFW_PBK_COPY_ENTRIES_RSP (EV_CFW_PBK_RSP_BASE + 8)
#define EV_CFW_PBK_ADD_ENTRY_ITEM_RSP (EV_CFW_PBK_RSP_BASE + 9)
#define EV_CFW_PBK_GET_ENTRY_ITEMS_RSP (EV_CFW_PBK_RSP_BASE + 10)
#define EV_CFW_PBK_DELETE_ENTRY_ITEM_RSP (EV_CFW_PBK_RSP_BASE + 11)
#define EV_CFW_PBK_ADD_CALLLOG_ENTTRY_RSP (EV_CFW_PBK_RSP_BASE + 12)
#define EV_CFW_PBK_GET_CALLLOG_ENTRY_RSP (EV_CFW_PBK_RSP_BASE + 13)
#define EV_CFW_PBK_LIST_CALLLOG_ENTRIES_RSP (EV_CFW_PBK_RSP_BASE + 14)
#define EV_CFW_PBK_DELETE_CALLLOG_ALL_ENTRIES_RSP (EV_CFW_PBK_RSP_BASE + 15)
#define EV_CFW_PBK_CANCEL_RSP (EV_CFW_PBK_RSP_BASE + 16)
#define EV_CFW_PBK_DELETE_CALLLOG_OLDEST_ENTRY_RSP (EV_CFW_PBK_RSP_BASE + 17)
//
// Shell Response Event
//
#define EV_CFW_ME_SET_FACILITY_LOCK_RSP (EV_CFW_SHELL_RSP_BASE + 1)
#define EV_CFW_ME_GET_FACILITY_LOCK_RSP (EV_CFW_SHELL_RSP_BASE + 2)
#define EV_CFW_ME_CHANGE_PWD_RSP (EV_CFW_SHELL_RSP_BASE + 3)

//
//TCP(UDP) / IP Event
//
#define EV_CFW_TCPIP_SOCKET_CONNECT_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 1)
#define EV_CFW_TCPIP_SOCKET_CLOSE_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 2)
#define EV_CFW_TCPIP_SOCKET_SEND_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 3)

//
#define EV_CFW_FTP_LONGIN_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 4)
#define EV_CFW_FTP_FILE_DOWNLOAD_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 5)
#define EV_CFW_FTP_LIST_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 6)
#define EV_CFW_FTP_CHANGEDIR_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 7)
#define EV_CFW_FTP_REC_DATA_IND (EV_CFW_TCPIPUDP_RSP_BASE + 8)
#define EV_CFW_FTP_REQUEST_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 9)
#define EV_CFW_FTP_SIZE_RSP (EV_CFW_TCPIPUDP_RSP_BASE + 10)
#define EV_CFW_FTP_DATA_CONNECT (EV_CFW_TCPIPUDP_RSP_BASE + 11)
#define EV_CFW_FTP_SOCKET_CLOSE (EV_CFW_TCPIPUDP_RSP_BASE + 12)

//
//test mode event
//
#define EV_CFW_TSM_INFO_IND (EV_CFW_TM_RSP_BASE + 1)
#define EV_CFW_TSM_INFO_END_RSP (EV_CFW_TM_RSP_BASE + 2)
#define EV_CFW_TSM_SYNC_INFO_IND (EV_CFW_TM_RSP_BASE + 3)
#define EV_CFW_TSM_SYNC_INFO_END_RSP (EV_CFW_TM_RSP_BASE + 4)
#define EV_RMT_STTPC_REQ (EV_RMC_BASE + 1)
#define EV_RMT_STTPC_RSP (EV_RMC_BASE + 2)

#define EV_RMT_APP_REQ (EV_RMC_BASE + 51)
#define EV_RMT_APP_RSP (EV_RMC_BASE + 52)

#define EV_DIAG_RECEIVE_DATA (EV_RMC_BASE + 60)
#define EV_DIAG_SEND_DATA (EV_RMC_BASE + 61)
#define EV_DIAG_RECEIVE_AT (EV_RMC_BASE + 62)
#define EV_DIAG_SEND_AT (EV_RMC_BASE + 63)

#define EV_WATCH_RECEIVE_DATA (EV_RMC_BASE + 64)
#ifdef __MMI_R_WATCH_SERVICE__
#define WETALK_RECEIVE_FILE_NUM (EV_RMC_BASE + 65)
#define EV_WATCH_RECEIVE_REFRESH_IDLE (EV_RMC_BASE + 66)
#endif
#define EV_CFW_WIFI_INIT_RSP (EV_WIFI_RSP_BASE + 1)
#define EV_CFW_WIFI_DEINIT_RSP (EV_WIFI_RSP_BASE + 2)
#ifdef WIFI_SUPPORT
#define EV_CFW_WIFI_SCAN_RSP (EV_WIFI_RSP_BASE + 3)
#define EV_CFW_WIFI_CONN_RSP (EV_WIFI_RSP_BASE + 4)
#define EV_CFW_WIFI_DISCONN_RSP (EV_WIFI_RSP_BASE + 5)
#define EV_CFW_WIFI_DISCONNECT_IND (EV_WIFI_RSP_BASE + 6)

#define EV_CFW_WIFI_SCAN_REQ (EV_WIFI_RSP_BASE + 7)
#define EV_CFW_WIFI_CONNECT_REQ (EV_WIFI_RSP_BASE + 8)
#define EV_CFW_WIFI_POWER_ON_REQ (EV_WIFI_RSP_BASE + 9)
#define EV_CFW_WIFI_IPADDR_CHANGE_REQ (EV_WIFI_RSP_BASE + 10)

#define EV_CFW_WIFI_CONNECTED_IND (EV_WIFI_IND_BASE + 1)
#define EV_CFW_WIFI_DATA_IND (EV_WIFI_IND_BASE + 2)
#define EV_CFW_WIFI_TEST_MODE_DATA_IND (EV_WIFI_IND_BASE + 3)
#define EV_MAC_WIFI_DATA_IND (EV_WIFI_IND_BASE + 4)
#define EV_MAC_WIFI_DATA_REQ (EV_WIFI_IND_BASE + 5)
#define EV_CFW_WIFI_EAPOL_IND (EV_WIFI_IND_BASE + 6)
#define EV_CFW_WIFI_NEED_POWEROFF_IND (EV_WIFI_IND_BASE + 8)
#define EV_CFW_WIFI_IPADDR_UPDATE_IND (EV_WIFI_IND_BASE + 9)

#define EV_CFW_WIFI_IPADDR_CONFLICT_IND (EV_WIFI_IND_BASE + 10)

#define EV_CFW_WIFI_CURR_AP_INFO_IND (EV_WIFI_IND_BASE + 11)

#define EV_CFW_WIFI_RESET_REQ (EV_WIFI_IND_BASE + 12)

#define EV_WIFI_MMI_RESET_IND (EV_WIFI_IND_BASE + 13)

#define EV_CFW_WIFI_DISCONNECT_REQ (EV_WIFI_IND_BASE + 14)
#define EV_WIFI_WIFI_POWERON_CONTINUE_REQ (EV_WIFI_IND_BASE + 15)
#define EV_CFW_WIFI_POWER_OFF_REQ (EV_WIFI_IND_BASE + 16)
#define EV_MAC_WIFI_KET_SET_REQ (EV_WIFI_IND_BASE + 17)

#define EV_CFW_WIFI_TEST_MODE_INFO_IND (EV_WIFI_IND_BASE + 18)
#define EV_CFW_WIFI_GET_NETWORKINFO_REQ (EV_WIFI_IND_BASE + 19)

#define EV_CFW_WIFI_SCAN_SINGLE_RSP (EV_WIFI_IND_BASE + 20)
#define EV_CFW_WIFI_SCAN_COMPLETE (EV_WIFI_IND_BASE + 21)
#define EV_CFW_WIFI_FRAME_IND (EV_WIFI_IND_BASE + 22)
#define EV_CFW_WIFI_POWERON_CONTINUE_REQ (EV_WIFI_IND_BASE + 23)
#define EV_CFW_WIFI_SMART_CONFIG_COMPL (EV_WIFI_IND_BASE + 24)
#define EV_CFW_WIFI_SNIFFER_COMPL (EV_WIFI_IND_BASE + 25)

#endif

#ifdef BT_TETHER_SUPPORT

#define EV_BT_TETHER_DATA_IND (EV_BT_TETHER_BASE + 1)
#define EV_BT_TETHER_END_ (1450)

#endif
#ifdef BT_ENABLE
typedef enum
{
    MSG_ID_BT_NOTIFY_EVM_IND = EV_MSG_ID_BT_BASE,
   MSG_ID_BT_ENABLE_BRDUT,
   MSG_ID_BT_LE_TST_RESET_REQ,
   MSG_ID_BT_LE_RX_MODE_REQ,
   MSG_ID_BT_LE_TX_MOD_REQ,
   MSG_ID_BT_LE_ENDTEST,    MSG_ID_BT_POWERON_REQ,
    MSG_ID_BT_POWERON_CNF,
    MSG_ID_BT_ENGINEER_MODE_POWERON_REQ,
    MSG_ID_BT_ENGINEER_MODE_POWERON_CNF,
    MSG_ID_BT_POWEROFF_REQ,
    MSG_ID_BT_POWEROFF_IND,
    MSG_ID_BT_POWEROFF_CNF,
    #ifdef MMI_ONLY_AT
    MSG_ID_UART_READY_TO_READ_IND,
    #endif
    MSG_ID_BT_ENGINEER_MODE_POWEROFF_REQ,
    MSG_ID_BT_ENGINEER_MODE_POWEROFF_CNF,
    MSG_ID_BT_RESET_REQ_IND,
    MSG_ID_BT_MMI_RESET_REQ,
    MSG_ID_BT_MMI_RESET_CNF,
    MSG_ID_BT_L4C_RESET_REQ,
    MSG_ID_BT_L4C_RESET_CNF,
    MSG_ID_BT_RESTART_REQ,
    MSG_ID_BT_READY_IND,
    MSG_ID_BT_DATA_TO_READ_IND,
    MSG_ID_BT_HOST_WAKE_UP_IND,
    MSG_ID_BT_WIFI_SET_CHNL_REQ,
    MSG_ID_BT_JSR_ACTIVE_REQ,
    MSG_ID_BT_JSR_ACTIVE_CNF,
    MSG_ID_BT_JSR_DEACTIVE_REQ,
    MSG_ID_BT_JSR_DEACTIVE_CNF,
    MSG_ID_BT_JSR_TEST_INIF_REQ,
    MSG_ID_BT_JSR_TEST_CMD1_REQ,
    MSG_ID_BT_JSR_TEST_CMD2_REQ,
    MSG_ID_BT_JSR_TEST_CMD3_REQ,
    MSG_ID_BT_JSR_TEST_CMD4_REQ,
    MSG_ID_BT_JSR_TEST_CMD5_REQ,

    MSG_ID_BT_TEST_MODE_REQ,
    MSG_ID_BT_TEST_CMD_REQ,
    MSG_ID_BT_L4C_TEST_CMD_CNF,
    MSG_ID_BT_PCM_LB_REQ,
    MSG_ID_BT_PCM_LB_CNF,
    MSG_ID_BT_SET_BD_ADDR_REQ,
    MSG_ID_BT_SET_POWER_TABLE_REQ,
    MSG_ID_BT_SET_ANA_TRIM_REQ,
    MSG_ID_BT_L4C_AT_GENERAL_CNF,
    MSG_ID_BT_GET_BD_ADDR_REQ,
    MSG_ID_BT_GET_BD_ADDR_CNF,
    MSG_ID_BT_GET_BT_VERSION_REQ,
    MSG_ID_BT_GET_BT_VERSION_CNF,
    MSG_ID_BT_ENGINEER_MODE_CNF,
    MSG_ID_BT_ENGINEER_MODE_TXRX_TEST_REQ,
    MSG_ID_BT_ENGINEER_MODE_TXRX_TEST_CNF,
    MSG_ID_BT_ENGINEER_MODE_POWER_TEST_REQ,
    MSG_ID_BT_ENGINEER_MODE_POWER_TEST_CNF,
    MSG_TAG_BT_SAP_START_MSG,

    MSG_TAG_BT_SPP_FIRST_REQ_MSG,
    MSG_ID_BT_SPP_ACTIVATE_REQ = MSG_TAG_BT_SPP_FIRST_REQ_MSG,
    MSG_ID_BT_SPP_CONNECT_REQ,
    MSG_ID_BT_SPP_SCO_CONNECT_REQ,
    MSG_ID_BT_SPP_SEND_DATA_REQ,
    MSG_ID_BT_SPP_GET_DATA_REQ,
    MSG_ID_BT_SPP_DEACTIVATE_REQ,
    MSG_ID_BT_SPP_DISCONNECT_REQ,
    MSG_ID_BT_SPP_AUDIO_CONNECT_REQ,
    MSG_ID_BT_SPP_AUDIO_DISCONNECT_REQ,
    MSG_ID_BT_SPP_AUTH_RSP,

    MSG_ID_BT_SPP_UART_OWNER_CNF,

    MSG_ID_BT_SPP_UART_PLUGOUT_CNF,
    MSG_ID_BT_DUN_ACTIVATE_REQ,
    MSG_ID_BT_DUN_DEACTIVATE_REQ,
    MSG_ID_BT_DUN_DISCONNECT_REQ,
    MSG_ID_BT_DUN_AUTH_RSP,

    MSG_ID_BT_FAX_ACTIVATE_REQ,
    MSG_ID_BT_FAX_DEACTIVATE_REQ,
    MSG_ID_BT_FAX_DISCONNECT_REQ,
    MSG_ID_BT_FAX_AUTH_RSP,
    MSG_TAG_BT_SPP_LAST_REQ_MSG = MSG_ID_BT_FAX_AUTH_RSP,

    MSG_ID_BT_SPP_CONNECT_IND,
    MSG_ID_BT_SPP_SCO_CONNECT_IND,
    MSG_ID_BT_SPP_DISCONNECT_IND,
    MSG_ID_BT_SPP_ACTIVATE_CNF,
    MSG_ID_BT_SPP_DEACTIVATE_CNF,
    MSG_ID_BT_SPP_DISCONNECT_CNF,
    MSG_ID_BT_SPP_AUTH_REQ,
    MSG_ID_BT_SPP_AUDIO_CONNECT_CNF,
    MSG_ID_BT_SPP_AUDIO_CONNECT_IND,
    MSG_ID_BT_SPP_AUDIO_DISCONNECT_CNF,
    MSG_ID_BT_SPP_AUDIO_DISCONNECT_IND,
    MSG_ID_BT_SPP_SCO_RSSI_IND,
    MSG_ID_BT_SPP_CONNECT_CNF,

    MSG_ID_BT_SPP_UART_OWNER_IND,

    MSG_ID_BT_DUN_CONNECT_IND,
    MSG_ID_BT_DUN_DISCONNECT_IND,
    MSG_ID_BT_DUN_ACTIVATE_CNF,
    MSG_ID_BT_DUN_DEACTIVATE_CNF,
    MSG_ID_BT_DUN_DISCONNECT_CNF,
    MSG_ID_BT_DUN_AUTH_REQ,

    MSG_ID_BT_FAX_CONNECT_IND,
    MSG_ID_BT_FAX_DISCONNECT_IND,
    MSG_ID_BT_FAX_ACTIVATE_CNF,
    MSG_ID_BT_FAX_DEACTIVATE_CNF,
    MSG_ID_BT_FAX_DISCONNECT_CNF,
    MSG_ID_BT_FAX_AUTH_REQ,

    MSG_TAG_BT_BM_FIRST_REQ_MSG,
    MSG_ID_BT_BM_DISCOVERY_REQ = MSG_TAG_BT_BM_FIRST_REQ_MSG,
    MSG_ID_BT_BM_DISCOVERY_CANCEL_REQ,
    MSG_ID_BT_BM_WRITE_LOCAL_NAME_REQ,
    MSG_ID_BT_BM_READ_LOCAL_NAME_REQ,
    MSG_ID_BT_BM_READ_REMOTE_NAME_REQ,
    MSG_ID_BT_BM_WRITE_SCANENABLE_MODE_REQ,
    MSG_ID_BT_BM_READ_SCANENABLE_MODE_REQ,
    MSG_ID_BT_BM_READ_LOCAL_ADDR_REQ,
    MSG_ID_BT_BM_READ_LOCAL_COD_REQ,
    MSG_ID_BT_BM_WRITE_LOCAL_COD_REQ,
    MSG_ID_BT_BM_READ_PROPERTY_REQ,
    MSG_ID_BT_BM_WRITE_AUTHENTICATION_MODE_REQ,
    MSG_ID_BT_BM_PIN_CODE_RSP,
    MSG_ID_BT_BM_BONDING_REQ,
    MSG_ID_BT_BM_DELETE_TRUST_REQ,
    MSG_ID_BT_BM_DELETE_TRUST_ALL_REQ,
    MSG_ID_BT_BM_BONDING_CANCEL_REQ,
    MSG_ID_BT_BM_PAIRING_CANCEL_REQ,
#ifdef __MMI_BT_SIMPLE_PAIR__
    MSG_ID_BT_BM_SECURITY_USER_CONFIRM_IND,
    MSG_ID_BT_BM_SECURITY_USER_CONFIRM_RSP,
#endif
    MSG_ID_BT_BM_SAVE_SETTING_REQ,
    MSG_ID_BT_BM_RESTORE_SETTING_REQ,
    MSG_ID_BT_BM_SERVICE_SEARCH_REQ,
    MSG_ID_BT_BM_SEARCH_ATTRIBUTE_REQ,
    MSG_ID_BT_BM_SEARCH_RAW_REQ,
    MSG_ID_BT_BM_LINK_ALLOW_REQ,
    MSG_ID_BT_BM_LINK_DISALLOW_REQ,
    MSG_ID_BT_BM_LINK_CONNECT_ACCEPT_NOT_AUTO_REQ,
    MSG_ID_BT_BM_LINK_CONNECT_ACCEPT_RSP,
    MSG_ID_BT_BM_GET_LINK_STATE_REQ,
    MSG_ID_BT_BM_SET_LINK_STATE_REQ,
    MSG_TAG_BT_BM_LAST_REQ_MSG = MSG_ID_BT_BM_SET_LINK_STATE_REQ,

    /*BMA --> APP*/
    MSG_TAG_BT_BMAPP_FIRST_REQ_MSG,
    MSG_ID_BT_BM_DISCOVERY_RESULT_IND = MSG_TAG_BT_BMAPP_FIRST_REQ_MSG,
    MSG_ID_BT_BM_DISCOVERY_CNF,
    MSG_ID_BT_BM_DISCOVERY_CANCEL_CNF,
    MSG_ID_BT_BM_WRITE_LOCAL_NAME_CNF,
    MSG_ID_BT_BM_READ_LOCAL_NAME_CNF,
    MSG_ID_BT_BM_READ_REMOTE_NAME_CNF,
    MSG_ID_BT_BM_WRITE_SCANENABLE_MODE_CNF,
    MSG_ID_BT_BM_READ_SCANENABLE_MODE_CNF,
    MSG_ID_BT_BM_READ_LOCAL_ADDR_CNF,
    MSG_ID_BT_BM_READ_LOCAL_COD_CNF,
    MSG_ID_BT_BM_WRITE_LOCAL_COD_CNF,
    MSG_ID_BT_BM_READ_PROPERTY_CNF,
    MSG_ID_BT_BM_WRITE_AUTHENTICATION_MODE_CNF,
    MSG_ID_BT_BM_PIN_CODE_IND,
    MSG_ID_BT_BM_BONDING_CNF,
    MSG_ID_BT_BM_BE_BONDING_CNF,
    MSG_ID_BT_BM_BONDING_RESULT_IND,
    MSG_ID_BT_BM_DELETE_TRUST_CNF,
    MSG_ID_BT_BM_DELETE_TRUST_ALL_CNF,
    MSG_ID_BT_BM_BONDING_CANCEL_CNF,
    MSG_ID_BT_BM_PAIRING_CANCEL_CNF,
    MSG_ID_BT_BM_SAVE_SETTING_CNF,
    MSG_ID_BT_BM_RESTORE_SETTING_CNF,
    MSG_ID_BT_BM_SERVICE_SEARCH_RESULT_IND,
    MSG_ID_BT_BM_SERVICE_SEARCH_CNF,
    MSG_ID_BT_BM_SEARCH_ATTRIBUT_RESULT_IND,
    MSG_ID_BT_BM_SEARCH_ATTRIBUTE_CNF,
    MSG_ID_BT_BM_SEARCH_RAW_RESULT,
    MSG_ID_BT_BM_SEARCH_RAW_CNF,
    MSG_ID_BT_BM_LINK_STATE_IND,
    MSG_ID_BT_BM_LINK_ALLOW_CNF,
    MSG_ID_BT_BM_LINK_DISALLOW_CNF,
    MSG_ID_BT_BM_LINK_CONNECT_ACCEPT_IND,
    MSG_ID_BT_BM_LINK_DISCONNECT_IND,
    MSG_ID_BT_BM_GET_LINK_STATE_CNF,
    MSG_ID_BT_BM_SET_LINK_STATE_CNF,
    MSG_TAG_BT_BMAPP_LAST_REQ_MSG = MSG_ID_BT_BM_SET_LINK_STATE_CNF,

    /* APP --> HSG */
    MSG_TAG_BT_HSG_FIRST_REQ_MSG,
    MSG_ID_BT_HSG_ACTIVATE_REQ = MSG_TAG_BT_HSG_FIRST_REQ_MSG,
    MSG_ID_BT_HSG_DEACTIVATE_REQ,
    MSG_ID_BT_HSG_CONNECT_REQ,
    MSG_ID_BT_HSG_CONNECT_IND_RES,
    MSG_ID_BT_HSG_DISCONNECT_REQ,
    MSG_ID_BT_HSG_BUTTONPRESS_REQ,
    MSG_ID_BT_HSG_MVOLUMEDOWN_REQ,
    MSG_ID_BT_HSG_MVOLUMEUP_REQ,
    MSG_ID_BT_HSG_SVOLUMEDOWN_REQ,
    MSG_ID_BT_HSG_SVOLUMEUP_REQ,
    MSG_ID_BT_HSG_SPEAKER_GAIN_REQ,
    MSG_ID_BT_HSG_MIC_GAIN_REQ,
    MSG_TAG_BT_HSG_LAST_REQ_MSG = MSG_ID_BT_HSG_MIC_GAIN_REQ,

    /* APP <-- HSG */
    MSG_ID_BT_HSG_ACTIVATE_CNF,
    MSG_ID_BT_HSG_DEACTIVATE_CNF,
    MSG_ID_BT_HSG_CONNECT_CNF,
    MSG_ID_BT_HSG_CONNECT_IND,
    MSG_ID_BT_HSG_CONNECT_IND_REQ,
    MSG_ID_BT_HSG_DISCONNECT_CNF,
    MSG_ID_BT_HSG_DISCONNECT_IND,
    MSG_ID_BT_HSG_SPEAKER_GAIN_CNF,
    MSG_ID_BT_HSG_SPEAKER_GAIN_IND,
    MSG_ID_BT_HSG_MIC_GAIN_IND,
    MSG_ID_BT_HSG_MIC_GAIN_CNF,
    MSG_ID_BT_HSG_HANGUP_REQ,
    MSG_ID_BT_HSG_INCOMING_ACCEPT_REQ,

    /*APP --> HFG*/
    MSG_TAG_BT_HFG_FIRST_REQ_MSG,
    MSG_ID_BT_HFG_ACTIVATE_REQ = MSG_TAG_BT_HFG_FIRST_REQ_MSG,
    MSG_ID_BT_HFG_DEACTIVATE_REQ,
    MSG_ID_BT_HFG_DISCONNECT_REQ,
    MSG_ID_BT_HFG_CONNECT_REQ,
    MSG_ID_BT_HFG_CONNECT_IND_RES,
    MSG_ID_BT_HFG_SCO_CONNECT_REQ,
    MSG_ID_BT_HFG_SCO_DISCONNECT_REQ,
    MSG_ID_BT_HFG_SPEAKER_GAIN_REQ,
    MSG_ID_BT_HFG_MIC_GAIN_REQ,
    //  MSG_ID_BT_HFG_REDIAL_FIAL_IND,
    MSG_ID_BT_HFG_INCOMING_DISCONNECT_REQ,
    MSG_ID_BT_HFG_SEND_RING_REQ,
    MSG_ID_BT_HFG_SEND_STOP_RING_REQ,
    MSG_ID_BT_HFG_SEND_CALL_SETUP_REQ,
    MSG_ID_BT_HFG_SEND_CALL_SETUP_1_RES,
    MSG_ID_BT_HFG_SEND_CALL_END_REQ,
    MSG_ID_BT_HFG_BLDN_FAIL_RES,
    MSG_ID_BT_HFG_VTS_DTMF_IND,

#ifdef __BT_PROFILE_BQB__
    MSG_ID_BT_HFG_SEND_NETWORK_STATUS_REQ,
    MSG_ID_BT_HFG_SEND_SIGNAL_LEVEL_REQ,
    MSG_ID_BT_HFG_BATTERY_LEVEL_REQ,
#endif

    MSG_ID_BT_HFG_ATD_CALL_IND,
    MSG_ID_BT_HFG_BLDN_RES_STATUS,
    MSG_ID_BT_HFG_SECOND_CALL_ACTIVE,
    MSG_ID_BT_HFG_SECOND_CALL_REQ,

    MSG_ID_BT_HFG_CALL_SWAP,
    MSG_ID_BT_HFG_CALL_HOLD,
    MSG_ID_SEND_CALL_CIEV_REQ,

    MSG_ID_SEND_CALL_CLCC_RES,

#ifdef __SUPPORT_BT_PHONE__
    MSG_ID_BT_PHONE_CALL_INFO_IND,
    MSG_ID_BT_PHONE_SCO_INFO_IND,
    MSG_ID_BT_PHONE_SEND_CHUP_REQ,
    MSG_ID_BT_PHONE_SEND_DIAL_NUMBER_REQ,
    MSG_ID_BT_PHONE_SEND_CALL_ANSWER_REQ,
    MSG_ID_BT_PHONE_SEND_DTMF_REQ,
    MSG_ID_BT_PHONE_AUTO_CON_REQ,
    MSG_ID_BT_PHONE_VOIE_CHANGE_TO_PHONE,
    MSG_ID_BT_PHONE_VOIE_CHANGE_TO_LOCAL,
#ifdef __SUPPORT_BT_SYNC_PHB__
    MSG_ID_BT_PBAP_CON_REQ,
    MSG_ID_BT_PBAP_DISCON_REQ,
    MSG_ID_BT_PBAP_DATA_IND,
    MSG_ID_BT_PBAP_GET_NEXT_REQ,
    MSG_ID_BT_PBAP_DISCON_CNF,
#endif
#ifdef __SUPPORT_BT_SYNC_MAP__

    MSG_ID_BT_MAP_CON_REQ,
    MSG_ID_BT_MAP_DISCON_REQ,
    MSG_ID_BT_MAP_DATA_IND,
    MSG_ID_BT_MAP_DISCON_CNF,
#endif
#endif
    MSG_ID_BT_PHONE_SCO_DATA_SEND_REQ,

    MGS_ID_BT_HFP_SET_CALL_NUM_REQ,

    MSG_ID_BT_HFG_SEND_NO_CARRIER_REQ,
    MSG_ID_HFP_CON_AUTHORIZE_RES,

    MSG_ID_BT_HFG_SEND_DATA_REQ,
    MSG_TAG_BT_HFG_LAST_REQ_MSG = MSG_ID_BT_HFG_SEND_DATA_REQ,

    /*APP <-- HFG*/
    MSG_ID_BT_HFG_ACTIVATE_CNF,
    MSG_ID_BT_HFG_DEACTIVATE_CNF,
    MSG_ID_BT_HFG_CONNECT_CNF,
    MSG_ID_BT_HFG_CONNECT_IND,
    MSG_ID_BT_HFG_SLC_FINISH_IND,
    MSG_ID_BT_HFG_CONNECT_IND_REQ,
    MSG_ID_BT_HFG_DISCONNECT_CNF,
    MSG_ID_BT_HFG_DISCONNECT_IND,
    MSG_ID_BT_HFG_SCO_CONNECT_CNF,
    MSG_ID_BT_HFG_SCO_CONNECT_IND,
    MSG_ID_BT_HFG_SCO_DISCONNECT_CNF,
    MSG_ID_BT_HFG_SCO_DISCONNECT_IND,
    MSG_ID_BT_HFG_SPEAKER_GAIN_CNF,
    MSG_ID_BT_HFG_SPEAKER_GAIN_IND,
    MSG_ID_BT_HFG_MIC_GAIN_IND,
    MSG_ID_BT_HFG_MIC_GAIN_CNF,
    MSG_ID_BT_HFG_HANGUP_REQ,
    MSG_ID_BT_HFG_INCOMING_ACCEPT_REQ,
    MSG_ID_BT_HFG_INCOMING_REJECT_REQ,
    MSG_ID_BT_HFG_REDIAL_LASTNUMB_REQ,
    MSG_ID_BT_HFG_ACTIVE_CALL_CHLD_IND,
    MSG_ID_HFP_NUMBER_CALL_IND,
    MSG_ID_HFP_CON_AUTHORIZE_IND,
    /*APP --> HIDD*/
    MSG_TAG_BT_HIDD_FIRST_REQ_MSG,
    MSG_ID_BT_HIDD_ACTIVATE_REQ = MSG_TAG_BT_HIDD_FIRST_REQ_MSG,
    MSG_ID_BT_HIDD_DEACTIVATE_REQ,
    MSG_ID_BT_HIDD_CONNECT_REQ,
    MSG_ID_BT_HIDD_CONNECTION_AUTHORIZE_RSP,
    MSG_ID_BT_HIDD_CONTROL_REQ,
    MSG_ID_BT_HIDD_DISCONNECT_REQ,
    MSG_ID_BT_HIDD_INTERRUPT_DATA_REQ,
    MSG_ID_BT_HIDD_GET_REPORT_RSP,
    MSG_ID_BT_HIDD_SET_REPORT_RSP,
    MSG_ID_BT_HIDD_GET_PROTOCOL_RSP,
    MSG_ID_BT_HIDD_SET_PROTOCOL_RSP,
    MSG_ID_BT_HIDD_GET_IDLE_RATE_RSP,
    MSG_ID_BT_HIDD_SET_IDLE_RATE_RSP,
    MSG_TAG_BT_HIDD_LAST_REQ_MSG = MSG_ID_BT_HIDD_SET_IDLE_RATE_RSP,

    /*APP <-- HIDD*/
    MSG_ID_BT_HIDD_ACTIVATE_CNF,
    MSG_ID_BT_HIDD_DEACTIVATE_CNF,
    MSG_ID_BT_HIDD_CONNECT_CNF,
    MSG_ID_BT_HIDD_CONNECT_IND,
    MSG_ID_BT_HIDD_CONNECTION_AUTHORIZE_IND,
    MSG_ID_BT_HIDD_DISCONNECT_CNF,
    MSG_ID_BT_HIDD_DISCONNECT_IND,
    MSG_ID_BT_HIDD_CONTROL_CNF,
    MSG_ID_BT_HIDD_CONTROL_IND,
    MSG_ID_BT_HIDD_INTERRUPT_DATA_CNF,
    MSG_ID_BT_HIDD_INTERRUPT_DATA_IND,
    MSG_ID_BT_HIDD_GET_REPORT_IND,
    MSG_ID_BT_HIDD_SET_REPORT_IND,
    MSG_ID_BT_HIDD_GET_PROTOCOL_IND,
    MSG_ID_BT_HIDD_SET_PROTOCOL_IND,
    MSG_ID_BT_HIDD_GET_IDLE_RATE_IND,
    MSG_ID_BT_HIDD_SET_IDLE_RATE_IND,

    /*APP --> AVRCP*/
    MSG_TAG_BT_AVCTP_FIRST_REQ_MSG,
    MSG_ID_BT_AVCTP_ACTIVATE_REQ = MSG_TAG_BT_AVCTP_FIRST_REQ_MSG,
    MSG_ID_BT_AVCTP_INIT_REQ,
    MSG_ID_BT_AVCTP_CONNECT_REQ,
    MSG_ID_BT_AVCTP_CONNECT_RSP,
    MSG_ID_BT_AVCTP_DISCONNECT_REQ,
    MSG_ID_BT_AVCTP_DATA_REQ,
    MSG_TAG_BT_AVCTP_LAST_REQ_MSG = MSG_ID_BT_AVCTP_DATA_REQ,

    /*A2DP*/
    // for MMI
    MSG_ID_BT_A2DP_ACTIVATE_REQ,
    MSG_ID_BT_A2DP_ACTIVATE_CNF,
    MSG_ID_BT_A2DP_DEACTIVATE_REQ,
    MSG_ID_BT_A2DP_DEACTIVATE_CNF,
    MSG_ID_BT_A2DP_SIGNAL_CONNECT_REQ,
    MSG_ID_BT_A2DP_SIGNAL_CONNECT_CNF,
    MSG_ID_BT_A2DP_SIGNAL_CONNECT_IND,
    MSG_ID_BT_A2DP_SIGNAL_DISCONNECT_REQ,
    MSG_ID_BT_A2DP_SIGNAL_DISCONNECT_CNF,
    MSG_ID_BT_A2DP_SIGNAL_DISCONNECT_IND,
    MSG_ID_BT_A2DP_NEED_CONNECT_IND,
    // for MED
    MSG_ID_BT_A2DP_SEP_DISCOVER_REQ,
    MSG_ID_BT_A2DP_SEP_DISCOVER_CNF,
    MSG_ID_BT_A2DP_SEP_DISCOVER_IND,
    MSG_ID_BT_A2DP_SEP_DISCOVER_RES,
    MSG_ID_BT_A2DP_CAPABILITIES_GET_REQ,
    MSG_ID_BT_A2DP_CAPABILITIES_GET_CNF,
    MSG_ID_BT_A2DP_CAPABILITIES_GET_IND,
    MSG_ID_BT_A2DP_CAPABILITIES_GET_RES,
    MSG_ID_BT_A2DP_STREAM_CONFIG_REQ,
    MSG_ID_BT_A2DP_STREAM_CONFIG_CNF,
    MSG_ID_BT_A2DP_STREAM_CONFIG_IND,
    MSG_ID_BT_A2DP_STREAM_CONFIG_RES,
    MSG_ID_BT_A2DP_STREAM_RECONFIG_REQ,
    MSG_ID_BT_A2DP_STREAM_RECONFIG_CNF,
    MSG_ID_BT_A2DP_STREAM_RECONFIG_IND,
    MSG_ID_BT_A2DP_STREAM_RECONFIG_RES,
    MSG_ID_BT_A2DP_STREAM_OPEN_REQ,
    MSG_ID_BT_A2DP_STREAM_OPEN_CNF,
    MSG_ID_BT_A2DP_STREAM_OPEN_IND,
    MSG_ID_BT_A2DP_STREAM_OPEN_RES,
    MSG_ID_BT_A2DP_STREAM_START_REQ,
    MSG_ID_BT_A2DP_STREAM_START_CNF,
    MSG_ID_BT_A2DP_STREAM_START_IND,
    MSG_ID_BT_A2DP_STREAM_START_RES,
    MSG_ID_BT_A2DP_STREAM_PAUSE_REQ,
    MSG_ID_BT_A2DP_STREAM_PAUSE_CNF,
    MSG_ID_BT_A2DP_STREAM_PAUSE_IND,
    MSG_ID_BT_A2DP_STREAM_PAUSE_RES,
    MSG_ID_BT_A2DP_STREAM_QOS_IND,
    MSG_ID_BT_A2DP_STREAM_DATA_SEND_REQ,
    MSG_ID_BT_A2DP_STREAM_CLOSE_REQ,
    MSG_ID_BT_A2DP_STREAM_CLOSE_CNF,
    MSG_ID_BT_A2DP_STREAM_CLOSE_IND,
    MSG_ID_BT_A2DP_STREAM_CLOSE_RES,
    MSG_ID_BT_A2DP_STREAM_ABORT_REQ,
    MSG_ID_BT_A2DP_STREAM_ABORT_CNF,
    MSG_ID_BT_A2DP_STREAM_ABORT_IND,
#ifdef __SUPPORT_BT_A2DP_SNK__
    MSG_ID_BT_PHONE_A2DP_SNK_PLAY_REQ,
    MSG_ID_A2DP_DATA_COMPLETED_MSG,
#endif
    MSG_ID_BT_A2DP_STREAM_ABORT_RES,

    /*AVRCP*/
    MSG_ID_BT_AVRCP_ACTIVATE_REQ,
    MSG_ID_BT_AVRCP_ACTIVATE_CNF,
    MSG_ID_BT_AVRCP_DEACTIVATE_REQ,
    MSG_ID_BT_AVRCP_DEACTIVATE_CNF,
    MSG_ID_BT_AVRCP_CONNECT_REQ,
    MSG_ID_BT_AVRCP_CONNECT_CNF,
    MSG_ID_BT_AVRCP_CONNECT_IND,
#ifdef __SUPPORT_BT_A2DP_SNK__
    MSG_ID_BT_AVRCP_STATUS_IND,
#endif
    MSG_ID_BT_AVRCP_CONNECT_IND_RES,
    MSG_ID_BT_AVRCP_DISCONNECT_REQ,
    MSG_ID_BT_AVRCP_DISCONNECT_CNF,
    MSG_ID_BT_AVRCP_DISCONNECT_IND,
    MSG_ID_BT_AVRCP_CMD_FRAME_REQ,
    MSG_ID_BT_AVRCP_CMD_FRAME_CNF,
    MSG_ID_BT_AVRCP_CMD_FRAME_IND,
    MSG_ID_BT_AVRCP_CMD_FRAME_IND_RES,
    MSG_ID_BT_GATT_SEND_NOTIFY_REQ,
    MSG_ID_BT_GATT_SEND_INDICATE_REQ,
    MSG_ID_BT_GATT_SET_ADV_DATA_REQ,
    MSG_ID_BT_GATT_ADD_SERVICE_REQ,
    MSG_ID_BT_GATT_SET_VISIBLE_REQ,
    MSG_ID_BT_GATT_SET_VISIBLE_CNF,
    MSG_ID_BT_GATT_MSG_INFO_IND,

    MSG_TAG_BT_TEST_FIRST_REQ_MSG,
    MSG_ID_BT_SDP_TEST_ACTIVATE_REQ = MSG_TAG_BT_TEST_FIRST_REQ_MSG,
    MSG_ID_BT_SDP_TEST_CLOSE_REQ,
    MSG_ID_BT_RFCOMM_TEST_ACTIVATE_REQ,
    MSG_ID_BT_L2CAP_TEST_CMD_REQ,
    MSG_ID_BT_GAP_TEST_CMD_REQ,
    MSG_ID_BT_AVDTP_TEST_CMD_REQ,
    MSG_ID_BT_JBT_TEST_CMD_REQ,
    MSG_ID_BT_SIMAP_TEST_ACTIVATE_REQ,
    MSG_TAG_BT_TEST_LAST_REQ_MSG = MSG_ID_BT_SIMAP_TEST_ACTIVATE_REQ,

    MSG_TAG_BT_SDPDB_FIRST_REQ_MSG,
    MSG_ID_BT_SDPDB_REGISTER_REQ = MSG_TAG_BT_SDPDB_FIRST_REQ_MSG,
    MSG_ID_BT_SDPDB_DEREGISTER_REQ,
    MSG_TAG_BT_SDPDB_LAST_REQ_MSG = MSG_ID_BT_SDPDB_DEREGISTER_REQ,
    MSG_ID_BT_SDPDB_REGISTER_CNF,
    MSG_ID_BT_SDPDB_DEREGISTER_CNF,

    /* JSR82 SDPDB REGISTERATION */
    MSG_TAG_BT_APP_SDPDB_FIRST_MSG,
    MSG_ID_BT_APP_SDPDB_GET_HANDLE_REQ = MSG_TAG_BT_APP_SDPDB_FIRST_MSG,
    MSG_ID_BT_APP_SDPDB_REGISTER_REQ,
    MSG_ID_BT_APP_SDPDB_RETRIEVE_RECOED_REQ,
    MSG_ID_BT_APP_SDPDB_DEREGISTER_REQ,
    MSG_ID_BT_APP_SDPDB_GET_HANDLE_CNF,
    MSG_ID_BT_APP_SDPDB_REGISTER_CNF,
    MSG_ID_BT_APP_SDPDB_RETRIEVE_RECOED_CNF,
    MSG_ID_BT_APP_SDPDB_DEREGISTER_CNF,
    MSG_TAG_BT_APP_SDPDB_LAST_MSG = MSG_ID_BT_APP_SDPDB_DEREGISTER_CNF,

    /* JSR82 SECURITY REGISTERATION */
    MSG_TAG_BT_JSR82_SEC_FIRST_MSG,
    MSG_ID_BT_JSR82_AUTHENTICATION_REQ = MSG_TAG_BT_JSR82_SEC_FIRST_MSG,
    MSG_ID_BT_JSR82_AUTHORIZATION_REQ,
    MSG_ID_BT_JSR82_ENCRYPTION_REQ,
    MSG_ID_BT_JSR82_AUTHENTICATION_CNF,
    MSG_ID_BT_JSR82_AUTHORIZATION_CNF,
    MSG_ID_BT_JSR82_ENCRYPTION_CNF,
    MSG_TAG_BT_SEC_LAST_MSG = MSG_ID_BT_JSR82_ENCRYPTION_CNF,

    /*GOEP*/
    MSG_ID_GOEP_REGISTER_SERVER_REQ,
    MSG_ID_GOEP_REGISTER_SERVER_RSP,
    MSG_ID_GOEP_DEREGISTER_SERVER_REQ,
    MSG_ID_GOEP_DEREGISTER_SERVER_RSP,
    MSG_ID_GOEP_CONNECT_IND,
    MSG_ID_GOEP_CONNECT_RES,
    MSG_ID_GOEP_PUSH_IND,
    MSG_ID_GOEP_PUSH_RES,
    MSG_ID_GOEP_PULL_IND,
    MSG_ID_GOEP_PULL_RES,
    MSG_ID_GOEP_SET_FOLDER_IND,
    MSG_ID_GOEP_SET_FOLDER_RES,
    MSG_ID_GOEP_ABORT_IND,
    MSG_ID_GOEP_ABORT_RES,
    MSG_ID_GOEP_AUTH_REQ,
    MSG_ID_GOEP_AUTH_RSP,
    MSG_ID_GOEP_REGISTER_CLIENT_REQ,
    MSG_ID_GOEP_REGISTER_CLIENT_RSP,
    MSG_ID_GOEP_DEREGISTER_CLIENT_REQ,
    MSG_ID_GOEP_DEREGISTER_CLIENT_RSP,
    MSG_ID_GOEP_CONNECT_REQ,
    MSG_ID_GOEP_CONNECT_RSP,
    MSG_ID_GOEP_PUSH_REQ,
    MSG_ID_GOEP_PUSH_RSP,
    MSG_ID_GOEP_PULL_REQ,
    MSG_ID_GOEP_PULL_RSP,
    MSG_ID_GOEP_SET_FOLDER_REQ,
    MSG_ID_GOEP_SET_FOLDER_RSP,
    MSG_ID_GOEP_ABORT_REQ,
    MSG_ID_GOEP_ABORT_RSP,
    MSG_ID_GOEP_DISCONNECT_REQ,
    MSG_ID_GOEP_DISCONNECT_RSP,
    MSG_ID_GOEP_DISCONNECT_IND,
    MSG_ID_GOEP_DISCONNECT_RES,
    MSG_ID_GOEP_TPDISCONNECT_REQ,
    MSG_ID_GOEP_AUTH_IND,
    MSG_ID_GOEP_AUTH_RES,
    MSG_ID_GOEP_AUTHORIZE_IND,
    MSG_ID_GOEP_AUTHORIZE_RES,

    MSG_TAG_BT_APP_REG_SERVICE_FIRST_REQ_MSG,
    MSG_ID_BT_RECORD_REG_REQ = MSG_TAG_BT_APP_REG_SERVICE_FIRST_REQ_MSG,
    MSG_ID_BT_RECORD_UNREQ_REQ,
    MSG_ID_BT_RECORD_REQ_CNF,
    MSG_ID_BT_RECORD_UNREQ_CNF,
    MSG_TAG_BT_APP_REG_SERVICE_LAST_REQ_MSG = MSG_ID_BT_RECORD_UNREQ_CNF,

    /* SIM Access Profile : SIMAP */

    /* APP --> BT SIMAP */
    MSG_TAG_BT_SIMAP_FIRST_REQ_MSG,
    MSG_ID_BT_SIMAP_ACTIVATE_REQ = MSG_TAG_BT_SIMAP_FIRST_REQ_MSG,
    MSG_ID_BT_SIMAP_DEACTIVATE_REQ,
    MSG_ID_BT_SIMAP_AUTH_RSP,
    /* MSG_ID_BT_SIMAP_DISCONNECT_REQ: This msg is used to notify BT that the user wants to close the connection */
    MSG_ID_BT_SIMAP_DISCONNECT_REQ,
    MSG_TAG_BT_SIMAP_LAST_REQ_MSG = MSG_ID_BT_SIMAP_DISCONNECT_REQ,

    /* BT SIMAP --> APP */

    /* MSG_ID_BT_SIMAP_AUTH_REQ: This msg is used to let MMI ask the user to accept the remote connection or not */
    MSG_ID_BT_SIMAP_ACTIVATE_CNF,
    MSG_ID_BT_SIMAP_DEACTIVATE_CNF,
    MSG_ID_BT_SIMAP_AUTH_REQ,
    MSG_ID_BT_SIMAP_CONNECT_CNF,
    MSG_ID_BT_SIMAP_CONNECT_IND,
    MSG_ID_BT_SIMAP_DISCONNECT_CNF,
    /* MSG_ID_BT_SIMAP_DISCONNECT_IND: This msg is used to notify MMI that the connection is closed */
    MSG_ID_BT_SIMAP_DISCONNECT_IND,

    /* BT SIMAP -> SIM */
    MSG_ID_BT_SIM_CONNECT_REQ,
    MSG_ID_BT_SIM_RESET_REQ,
    MSG_ID_BT_SIM_APDU_REQ,
    MSG_ID_BT_SIM_DISCONNECT_REQ,
    MSG_ID_BT_SIM_POWER_OFF_REQ,

    /* SIM --> BT SIMAP */
    MSG_TAG_BT_SIM_FIRST_REQ_MSG,
    MSG_ID_BT_SIM_CONNECT_CNF = MSG_TAG_BT_SIM_FIRST_REQ_MSG,
    MSG_ID_BT_SIM_RESET_CNF,
    MSG_ID_BT_SIM_APDU_CNF,
    MSG_ID_BT_SIM_DISCONNECT_CNF,
    MSG_ID_BT_SIM_POWER_OFF_CNF,
    MSG_TAG_BT_SIM_LAST_REQ_MSG = MSG_ID_BT_SIM_POWER_OFF_CNF,

    /* JSR82 SESSION OPERATION */
    MSG_TAG_BT_JSR82_SECTION_FIRST_MSG,
    MSG_ID_BT_JSR82_CONNECT_REQ = MSG_TAG_BT_JSR82_SECTION_FIRST_MSG,
    MSG_ID_BT_JSR82_CONNECT_CFN,
    MSG_ID_BT_JSR82_ENABLE_SERVICE_REQ,
    MSG_ID_BT_JSR82_ENABLE_SERVICE_CNF,
    MSG_ID_BT_JSR82_TURNON_SERVICE_REQ,
    MSG_ID_BT_JSR82_TURNON_SERVICE_CNF,
    MSG_ID_BT_JSR82_DISABLE_SERVICE_REQ,
    MSG_ID_BT_JSR82_DISABLE_SERVICE_CNF,
    MSG_ID_BT_JSR82_CONNECT_IND,
    MSG_ID_BT_JSR82_CONNECT_RSP,
    MSG_ID_BT_JSR82_DISCONNECT_REQ,
    MSG_ID_BT_JSR82_DISCONNECT_IND,
    MSG_ID_BT_JSR82_TX_DATA_REQ,
    MSG_ID_BT_JSR82_TX_DATA_CFN,
    MSG_ID_BT_JSR82_RX_DATA_IND,
    MSG_ID_BT_JSR82_RX_DATA_RSP,
    MSG_TAG_BT_JSR82_SECTION_LAST_MSG = MSG_ID_BT_JSR82_RX_DATA_RSP,

    /* BPP */
    MSG_ID_BT_BPP_CONNECT_REQ,
    MSG_ID_BT_BPP_CONNECT_CNF,
    MSG_ID_BT_BPP_AUTHENTICATION_IND,
    MSG_ID_BT_BPP_AUTHENTICATION_RSP,
    MSG_ID_BT_BPP_DISCONNECT_REQ,
    MSG_ID_BT_BPP_DISCONNECT_IND,
    MSG_ID_BT_BPP_GET_PRINTER_ATTR_REQ,
    MSG_ID_BT_BPP_GET_PRINTER_ATTR_CNF,
    MSG_ID_BT_BPP_CREATE_JOB_REQ,
    MSG_ID_BT_BPP_CREATE_JOB_CNF,
    MSG_ID_BT_BPP_EVENT_IND,
    MSG_ID_BT_BPP_SEND_DOC_REQ,
    MSG_ID_BT_BPP_SEND_DOC_CNF,
    MSG_ID_BT_BPP_PROG_UPDATE_IND,
    MSG_ID_BT_BPP_PROG_UPDATE_RSP,

    /* BIP */
    MSG_ID_BT_BIP_CONNECT_REQ,
    MSG_ID_BT_BIP_CONNECT_CNF,
    MSG_ID_BT_BIP_DISCONNECT_REQ,
    MSG_ID_BT_BIP_GET_CAPABILITIES_REQ,
    MSG_ID_BT_BIP_GET_CAPABILITIES_CNF,
    MSG_ID_BT_BIP_PUT_IMG_REQ,
    MSG_ID_BT_BIP_PUT_IMG_CNF,
    MSG_ID_BT_BIP_PUT_LINKED_THUMBNAIL_REQ,
    MSG_ID_BT_BIP_PUT_LINKED_THUMBNAIL_CNF,
    MSG_ID_BT_BIP_GET_IMG_LIST_REQ,
    MSG_ID_BT_BIP_GET_IMG_LIST_CNF,
    MSG_ID_BT_BIP_GET_IMG_PROP_REQ,
    MSG_ID_BT_BIP_GET_IMG_PROP_CNF,
    MSG_ID_BT_BIP_GET_IMG_REQ,
    MSG_ID_BT_BIP_GET_IMG_CNF,
    MSG_ID_BT_BIP_GET_LINKED_THUMBNAIL_REQ,
    MSG_ID_BT_BIP_GET_LINKED_THUMBNAIL_CNF,
    MSG_ID_BT_BIP_GET_MONITORING_IMG_REQ,
    MSG_ID_BT_BIP_GET_MONITORING_IMG_CNF,
    MSG_ID_BT_BIP_ABORT_REQ,
    MSG_ID_BT_BIP_ABORT_CNF,
    MSG_ID_BT_BIP_ACTIVATE_REQ,
    MSG_ID_BT_BIP_ACTIVATE_CNF,
    MSG_ID_BT_BIP_DEACTIVATE_REQ,
    MSG_ID_BT_BIP_DEACTIVATE_CNF,
    MSG_ID_BT_BIP_CONNECT_IND,
    MSG_ID_BT_BIP_CONNECT_RSP,
    MSG_ID_BT_BIP_GET_CAPABILITIES_IND,
    MSG_ID_BT_BIP_GET_CAPABILITIES_RSP,
    MSG_ID_BT_BIP_PUT_IMG_IND,
    MSG_ID_BT_BIP_PUT_IMG_RSP,
    MSG_ID_BT_BIP_PUT_LINKED_THUMBNAIL_IND,
    MSG_ID_BT_BIP_PUT_LINKED_THUMBNAIL_RSP,
    MSG_ID_BT_BIP_GET_IMG_LIST_IND,
    MSG_ID_BT_BIP_GET_IMG_LIST_RSP,
    MSG_ID_BT_BIP_GET_IMG_PROP_IND,
    MSG_ID_BT_BIP_GET_IMG_PROP_RSP,
    MSG_ID_BT_BIP_GET_IMG_IND,
    MSG_ID_BT_BIP_GET_IMG_RSP,
    MSG_ID_BT_BIP_GET_LINKED_THUMBNAIL_IND,
    MSG_ID_BT_BIP_GET_LINKED_THUMBNAIL_RSP,
    MSG_ID_BT_BIP_GET_MONITORING_IMG_IND,
    MSG_ID_BT_BIP_GET_MONITORING_IMG_RSP,
    MSG_ID_BT_BIP_CONTINUE_IND,
    MSG_ID_BT_BIP_CONTINUE_RSP,
    MSG_ID_BT_BIP_ABORT_IND,
    MSG_ID_BT_BIP_COMPLETE_IND,
    MSG_ID_BT_BIP_DISCONNECT_IND,
#ifdef ATA_SUPPORT
    MSG_ID_BT_ENTER_BT_WINDOW_REQ,
    MSG_ID_BT_SERCH_BT_REQ,
#endif
    MSG_TAG_BT_SAP_END_MSG,

}rdabt_msg_type_enum;
#endif
#endif // _H_
