/* Copyright (C) 2018 RDA Technologies Limited and/or its affiliates("RDA").
* All rights reserved.
*
* This software is supplied "AS IS" without any warranties.
* RDA assumes no responsibility or liability for the use of the software,
* conveys no license or title under any patent, copyright, or mask work
* right to the product. RDA reserves the right to make changes in the
* software without notification.  RDA also make no representation or
* warranty that such application will be suitable for the specified use
* without further testing or modification.
*/

#ifndef _COS_LOG_H_
#define _COS_LOG_H_

#include <stdarg.h>

// trace level compile-time control macros
enum
{
    LOG_LEVEL_NEVER,
    LOG_LEVEL_ERROR,
    LOG_LEVEL_WARN,
    LOG_LEVEL_INFO,
    LOG_LEVEL_DEBUG,
    LOG_LEVEL_VERBOSE
};

#ifndef LOCAL_LOG_LEVEL
#define LOCAL_LOG_LEVEL LOG_LEVEL_INFO
#endif

#ifdef COS_LOG_DISABLED
#undef LOCAL_LOG_LEVEL
#define LOCAL_LOG_LEVEL LOG_LEVEL_NEVER
#endif

#define LOGE_EN (LOCAL_LOG_LEVEL >= LOG_LEVEL_ERROR)
#define LOGW_EN (LOCAL_LOG_LEVEL >= LOG_LEVEL_WARN)
#define LOGI_EN (LOCAL_LOG_LEVEL >= LOG_LEVEL_INFO)
#define LOGD_EN (LOCAL_LOG_LEVEL >= LOG_LEVEL_DEBUG)
#define LOGV_EN (LOCAL_LOG_LEVEL >= LOG_LEVEL_VERBOSE)

// trace module tag macros
#define MAKE_LOG_TAG(a, b, c, d) ((unsigned)(a) | ((unsigned)(b) << 7) | ((unsigned)(c) << 14) | ((unsigned)(d) << 21))

#ifndef LOCAL_LOG_TAG
#ifdef COS_LOG_TAG
#define LOCAL_LOG_TAG COS_LOG_TAG
#else
#define LOCAL_LOG_TAG LOG_TAG_NONE
#endif
#endif

// trace macros
#define COS_LOGE(fmtid, fmt, ...) __COS_LOGB(LOG_LEVEL_ERROR, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGW(fmtid, fmt, ...) __COS_LOGB(LOG_LEVEL_WARN, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGI(fmtid, fmt, ...) __COS_LOGB(LOG_LEVEL_INFO, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGD(fmtid, fmt, ...) __COS_LOGB(LOG_LEVEL_DEBUG, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGV(fmtid, fmt, ...) __COS_LOGB(LOG_LEVEL_VERBOSE, fmtid, fmt, ##__VA_ARGS__)

#define COS_LOGXE(partype, fmtid, fmt, ...) __COS_LOGX(LOG_LEVEL_ERROR, partype, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGXW(partype, fmtid, fmt, ...) __COS_LOGX(LOG_LEVEL_WARN, partype, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGXI(partype, fmtid, fmt, ...) __COS_LOGX(LOG_LEVEL_INFO, partype, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGXD(partype, fmtid, fmt, ...) __COS_LOGX(LOG_LEVEL_DEBUG, partype, fmtid, fmt, ##__VA_ARGS__)
#define COS_LOGXV(partype, fmtid, fmt, ...) __COS_LOGX(LOG_LEVEL_VERBOSE, partype, fmtid, fmt, ##__VA_ARGS__)

// printf: usually only for third-party codes.
// * support tag
// * same format as COS_LOG
// * string size is limited as COS_LOG
// * at most 16 parameters
#define COS_PRINTFE(fmt, ...) __COS_PRINTF(LOG_LEVEL_ERROR, fmt, ##__VA_ARGS__)
#define COS_PRINTFW(fmt, ...) __COS_PRINTF(LOG_LEVEL_WARN, fmt, ##__VA_ARGS__)
#define COS_PRINTFI(fmt, ...) __COS_PRINTF(LOG_LEVEL_INFO, fmt, ##__VA_ARGS__)
#define COS_PRINTFD(fmt, ...) __COS_PRINTF(LOG_LEVEL_DEBUG, fmt, ##__VA_ARGS__)
#define COS_PRINTFV(fmt, ...) __COS_PRINTF(LOG_LEVEL_VERBOSE, fmt, ##__VA_ARGS__)

// function for vprintf
void COS_Vprintf(unsigned tag, const char *fmt, va_list ap);

// trace parameter macro, count from 1 to 8. type can be
// I: int/short/char
// D: 64bits integer
// F: float/double
// S: string
// M: memory dump, parameter is (size, address)

// COS_LOGPAR_X/XX/XXX/XXXX are listed at the end of this file.
// When parameter count is larger than 4, the following macro can be used.
#define COS_LOGPAR(...) __COS_LOGPAR(__VA_ARGS__)

// pre-defined log tags
#define LOG_TAG_NONE MAKE_LOG_TAG(' ', ' ', ' ', ' ')
#define LOG_TAG_HAL MAKE_LOG_TAG('H', 'A', 'L', ' ')
#define LOG_TAG_DRV MAKE_LOG_TAG('D', 'R', 'V', ' ')
#define LOG_TAG_USB_SVC MAKE_LOG_TAG('S', 'U', 'S', 'B')
#define LOG_TAG_FILE_SYSTEM MAKE_LOG_TAG('F', 'S', 'Y', 'S')
#define LOG_TAG_ATE MAKE_LOG_TAG('A', 'T', 'E', 'N')
#define LOG_TAG_ATS MAKE_LOG_TAG('A', 'T', 'S', 'N')
#define LOG_TAG_MMI MAKE_LOG_TAG('M', 'M', 'I', ' ')
#define LOG_TAG_CSW MAKE_LOG_TAG('C', 'S', 'W', ' ')
// =============================================================================
// IMPLEMENTATION. DON'T USE THEM DIRECTLY
// =============================================================================

// Trace functions. Don't call them directly, use macros instead.
void COS_Trace(unsigned tag, unsigned nargs, const char *fmt, ...);
void COS_TraceX(unsigned tag, unsigned partype, const char *fmt, ...);
void COS_DTrace(unsigned tag, unsigned nargs, unsigned fmtid, ...);
void COS_DTraceX(unsigned tag, unsigned partype, unsigned fmtid, ...);
void COS_Printf(unsigned tag, const char *fmt, ...);

// Macro for variadic argument count
#ifndef _VA_NARGS
#define _VA_NARGS_IMPL(_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, N, ...) N
#define _VA_NARGS(...) _VA_NARGS_IMPL(0, ##__VA_ARGS__, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)
#endif

#ifdef COS_LOG_USE_PRINTF
extern int printf(const char *format, ...)  __attribute__ ((format (printf, 1, 2)));
#define __COS_LOGB(level, fmtid, fmt, ...) printf(fmt, ##__VA_ARGS__)
#define __COS_LOGX(level, partype, fmtid, fmt, ...) printf(fmt, ##__VA_ARGS__)
#define __COS_PRINTF(level, fmt, ...) printf(fmt, ##__VA_ARGS__)
#elif defined(COS_LOG_USE_PRINTF_PARAM_CHECK)
extern int _cos_printf_param_check(const char *format, ...)  __attribute__ ((format (printf, 1, 2)));
#define __COS_LOGB(level, fmtid, fmt, ...) _cos_printf_param_check(fmt, ##__VA_ARGS__)
#define __COS_LOGX(level, partype, fmtid, fmt, ...) _cos_printf_param_check(fmt, ##__VA_ARGS__)
#define __COS_PRINTF(level, fmt, ...) _cos_printf_param_check(fmt, ##__VA_ARGS__)
#else
#define __COS_LOGB(level, fmtid, fmt, ...)                                                                      \
    do                                                                                                          \
    {                                                                                                           \
        if (LOCAL_LOG_LEVEL >= level)                                                                           \
        {                                                                                                       \
            if (fmtid == 0)                                                                                     \
                __COS_LOGB_IMP((level << 28) | (LOCAL_LOG_TAG), _VA_NARGS(__VA_ARGS__), fmt, ##__VA_ARGS__);    \
            else                                                                                                \
                __COS_DLOGB_IMP((level << 28) | (LOCAL_LOG_TAG), _VA_NARGS(__VA_ARGS__), fmtid, ##__VA_ARGS__); \
        }                                                                                                       \
    } while (0)

#define __COS_LOGX(level, partype, fmtid, fmt, ...)                                              \
    do                                                                                           \
    {                                                                                            \
        if (LOCAL_LOG_LEVEL >= level)                                                            \
        {                                                                                        \
            if (fmtid == 0)                                                                      \
                __COS_LOGX_IMP((level << 28) | (LOCAL_LOG_TAG), partype, fmt, ##__VA_ARGS__);    \
            else                                                                                 \
                __COS_DLOGX_IMP((level << 28) | (LOCAL_LOG_TAG), partype, fmtid, ##__VA_ARGS__); \
        }                                                                                        \
    } while (0)
#define __COS_PRINTF(level, fmt, ...)                                        \
    do                                                                       \
    {                                                                        \
        if (LOCAL_LOG_LEVEL >= level)                                        \
            COS_Printf((level << 28) | (LOCAL_LOG_TAG), fmt, ##__VA_ARGS__); \
    } while (0)

#define __COS_LOGB_IMP(tag, nargs, fmt, ...) COS_Trace(tag, nargs, fmt, ##__VA_ARGS__)
#define __COS_DLOGB_IMP(tag, nargs, fmtid, ...) COS_DTrace(tag, nargs, fmtid, ##__VA_ARGS__)
#define __COS_LOGX_IMP(tag, partype, fmt, ...) COS_TraceX(tag, partype, fmt, ##__VA_ARGS__)
#define __COS_DLOGX_IMP(tag, partype, fmtid, ...) COS_DTraceX(tag, partype, fmtid, ##__VA_ARGS__)
#endif

enum
{
    __COS_LOGPAR_I = 1,
    __COS_LOGPAR_D = 2,
    __COS_LOGPAR_F = 3,
    __COS_LOGPAR_S = 4,
    __COS_LOGPAR_M = 5
};

#define __COS_LOGPAR_IMP2(count, ...) __COS_LOGPAR_X##count(__VA_ARGS__)
#define __COS_LOGPAR_IMP1(count, ...) __COS_LOGPAR_IMP2(count, __VA_ARGS__)
#define __COS_LOGPAR(...) __COS_LOGPAR_IMP1(_VA_NARGS(__VA_ARGS__), __VA_ARGS__)

#define __COS_LOGPAR_POS(n, p) (__COS_LOGPAR_##p << (n * 4))
#define __COS_LOGPAR_X1(a) (__COS_LOGPAR_POS(0, a))
#define __COS_LOGPAR_X2(a, b) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b))
#define __COS_LOGPAR_X3(a, b, c) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b) | __COS_LOGPAR_POS(2, c))
#define __COS_LOGPAR_X4(a, b, c, d) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b) | __COS_LOGPAR_POS(2, c) | __COS_LOGPAR_POS(3, d))
#define __COS_LOGPAR_X5(a, b, c, d, e) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b) | __COS_LOGPAR_POS(2, c) | __COS_LOGPAR_POS(3, d) | __COS_LOGPAR_POS(4, e))
#define __COS_LOGPAR_X6(a, b, c, d, e, f) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b) | __COS_LOGPAR_POS(2, c) | __COS_LOGPAR_POS(3, d) | __COS_LOGPAR_POS(4, e) | __COS_LOGPAR_POS(5, f))
#define __COS_LOGPAR_X7(a, b, c, d, e, f, g) (__COS_LOGPAR_POS(0, a) | __COS_LOGPAR_POS(1, b) | __COS_LOGPAR_POS(2, c) | __COS_LOGPAR_POS(3, d) | __COS_LOGPAR_POS(4, e) | __COS_LOGPAR_POS(5, f) | __COS_LOGPAR_POS(6, g))

/*
for a in I D F S M; do
    echo "#define COS_LOGPAR_${a} __COS_LOGPAR_X1($a)"
    for b in I D F S M; do
        echo "#define COS_LOGPAR_${a}${b} __COS_LOGPAR_X2($a, $b)"
        for c in I D F S M; do
            echo "#define COS_LOGPAR_${a}${b}${c} __COS_LOGPAR_X3($a, $b, $c)"
            for d in I D F S M; do
                echo "#define COS_LOGPAR_${a}${b}${c}${d} __COS_LOGPAR_X4($a, $b, $c, $d)"
            done
        done
    done
done
*/
#define COS_LOGPAR_I __COS_LOGPAR_X1(I)
#define COS_LOGPAR_II __COS_LOGPAR_X2(I, I)
#define COS_LOGPAR_III __COS_LOGPAR_X3(I, I, I)
#define COS_LOGPAR_IIII __COS_LOGPAR_X4(I, I, I, I)
#define COS_LOGPAR_IIID __COS_LOGPAR_X4(I, I, I, D)
#define COS_LOGPAR_IIIF __COS_LOGPAR_X4(I, I, I, F)
#define COS_LOGPAR_IIIS __COS_LOGPAR_X4(I, I, I, S)
#define COS_LOGPAR_IIIM __COS_LOGPAR_X4(I, I, I, M)
#define COS_LOGPAR_IID __COS_LOGPAR_X3(I, I, D)
#define COS_LOGPAR_IIDI __COS_LOGPAR_X4(I, I, D, I)
#define COS_LOGPAR_IIDD __COS_LOGPAR_X4(I, I, D, D)
#define COS_LOGPAR_IIDF __COS_LOGPAR_X4(I, I, D, F)
#define COS_LOGPAR_IIDS __COS_LOGPAR_X4(I, I, D, S)
#define COS_LOGPAR_IIDM __COS_LOGPAR_X4(I, I, D, M)
#define COS_LOGPAR_IIF __COS_LOGPAR_X3(I, I, F)
#define COS_LOGPAR_IIFI __COS_LOGPAR_X4(I, I, F, I)
#define COS_LOGPAR_IIFD __COS_LOGPAR_X4(I, I, F, D)
#define COS_LOGPAR_IIFF __COS_LOGPAR_X4(I, I, F, F)
#define COS_LOGPAR_IIFS __COS_LOGPAR_X4(I, I, F, S)
#define COS_LOGPAR_IIFM __COS_LOGPAR_X4(I, I, F, M)
#define COS_LOGPAR_IIS __COS_LOGPAR_X3(I, I, S)
#define COS_LOGPAR_IISI __COS_LOGPAR_X4(I, I, S, I)
#define COS_LOGPAR_IISD __COS_LOGPAR_X4(I, I, S, D)
#define COS_LOGPAR_IISF __COS_LOGPAR_X4(I, I, S, F)
#define COS_LOGPAR_IISS __COS_LOGPAR_X4(I, I, S, S)
#define COS_LOGPAR_IISM __COS_LOGPAR_X4(I, I, S, M)
#define COS_LOGPAR_IIM __COS_LOGPAR_X3(I, I, M)
#define COS_LOGPAR_IIMI __COS_LOGPAR_X4(I, I, M, I)
#define COS_LOGPAR_IIMD __COS_LOGPAR_X4(I, I, M, D)
#define COS_LOGPAR_IIMF __COS_LOGPAR_X4(I, I, M, F)
#define COS_LOGPAR_IIMS __COS_LOGPAR_X4(I, I, M, S)
#define COS_LOGPAR_IIMM __COS_LOGPAR_X4(I, I, M, M)
#define COS_LOGPAR_ID __COS_LOGPAR_X2(I, D)
#define COS_LOGPAR_IDI __COS_LOGPAR_X3(I, D, I)
#define COS_LOGPAR_IDII __COS_LOGPAR_X4(I, D, I, I)
#define COS_LOGPAR_IDID __COS_LOGPAR_X4(I, D, I, D)
#define COS_LOGPAR_IDIF __COS_LOGPAR_X4(I, D, I, F)
#define COS_LOGPAR_IDIS __COS_LOGPAR_X4(I, D, I, S)
#define COS_LOGPAR_IDIM __COS_LOGPAR_X4(I, D, I, M)
#define COS_LOGPAR_IDD __COS_LOGPAR_X3(I, D, D)
#define COS_LOGPAR_IDDI __COS_LOGPAR_X4(I, D, D, I)
#define COS_LOGPAR_IDDD __COS_LOGPAR_X4(I, D, D, D)
#define COS_LOGPAR_IDDF __COS_LOGPAR_X4(I, D, D, F)
#define COS_LOGPAR_IDDS __COS_LOGPAR_X4(I, D, D, S)
#define COS_LOGPAR_IDDM __COS_LOGPAR_X4(I, D, D, M)
#define COS_LOGPAR_IDF __COS_LOGPAR_X3(I, D, F)
#define COS_LOGPAR_IDFI __COS_LOGPAR_X4(I, D, F, I)
#define COS_LOGPAR_IDFD __COS_LOGPAR_X4(I, D, F, D)
#define COS_LOGPAR_IDFF __COS_LOGPAR_X4(I, D, F, F)
#define COS_LOGPAR_IDFS __COS_LOGPAR_X4(I, D, F, S)
#define COS_LOGPAR_IDFM __COS_LOGPAR_X4(I, D, F, M)
#define COS_LOGPAR_IDS __COS_LOGPAR_X3(I, D, S)
#define COS_LOGPAR_IDSI __COS_LOGPAR_X4(I, D, S, I)
#define COS_LOGPAR_IDSD __COS_LOGPAR_X4(I, D, S, D)
#define COS_LOGPAR_IDSF __COS_LOGPAR_X4(I, D, S, F)
#define COS_LOGPAR_IDSS __COS_LOGPAR_X4(I, D, S, S)
#define COS_LOGPAR_IDSM __COS_LOGPAR_X4(I, D, S, M)
#define COS_LOGPAR_IDM __COS_LOGPAR_X3(I, D, M)
#define COS_LOGPAR_IDMI __COS_LOGPAR_X4(I, D, M, I)
#define COS_LOGPAR_IDMD __COS_LOGPAR_X4(I, D, M, D)
#define COS_LOGPAR_IDMF __COS_LOGPAR_X4(I, D, M, F)
#define COS_LOGPAR_IDMS __COS_LOGPAR_X4(I, D, M, S)
#define COS_LOGPAR_IDMM __COS_LOGPAR_X4(I, D, M, M)
#define COS_LOGPAR_IF __COS_LOGPAR_X2(I, F)
#define COS_LOGPAR_IFI __COS_LOGPAR_X3(I, F, I)
#define COS_LOGPAR_IFII __COS_LOGPAR_X4(I, F, I, I)
#define COS_LOGPAR_IFID __COS_LOGPAR_X4(I, F, I, D)
#define COS_LOGPAR_IFIF __COS_LOGPAR_X4(I, F, I, F)
#define COS_LOGPAR_IFIS __COS_LOGPAR_X4(I, F, I, S)
#define COS_LOGPAR_IFIM __COS_LOGPAR_X4(I, F, I, M)
#define COS_LOGPAR_IFD __COS_LOGPAR_X3(I, F, D)
#define COS_LOGPAR_IFDI __COS_LOGPAR_X4(I, F, D, I)
#define COS_LOGPAR_IFDD __COS_LOGPAR_X4(I, F, D, D)
#define COS_LOGPAR_IFDF __COS_LOGPAR_X4(I, F, D, F)
#define COS_LOGPAR_IFDS __COS_LOGPAR_X4(I, F, D, S)
#define COS_LOGPAR_IFDM __COS_LOGPAR_X4(I, F, D, M)
#define COS_LOGPAR_IFF __COS_LOGPAR_X3(I, F, F)
#define COS_LOGPAR_IFFI __COS_LOGPAR_X4(I, F, F, I)
#define COS_LOGPAR_IFFD __COS_LOGPAR_X4(I, F, F, D)
#define COS_LOGPAR_IFFF __COS_LOGPAR_X4(I, F, F, F)
#define COS_LOGPAR_IFFS __COS_LOGPAR_X4(I, F, F, S)
#define COS_LOGPAR_IFFM __COS_LOGPAR_X4(I, F, F, M)
#define COS_LOGPAR_IFS __COS_LOGPAR_X3(I, F, S)
#define COS_LOGPAR_IFSI __COS_LOGPAR_X4(I, F, S, I)
#define COS_LOGPAR_IFSD __COS_LOGPAR_X4(I, F, S, D)
#define COS_LOGPAR_IFSF __COS_LOGPAR_X4(I, F, S, F)
#define COS_LOGPAR_IFSS __COS_LOGPAR_X4(I, F, S, S)
#define COS_LOGPAR_IFSM __COS_LOGPAR_X4(I, F, S, M)
#define COS_LOGPAR_IFM __COS_LOGPAR_X3(I, F, M)
#define COS_LOGPAR_IFMI __COS_LOGPAR_X4(I, F, M, I)
#define COS_LOGPAR_IFMD __COS_LOGPAR_X4(I, F, M, D)
#define COS_LOGPAR_IFMF __COS_LOGPAR_X4(I, F, M, F)
#define COS_LOGPAR_IFMS __COS_LOGPAR_X4(I, F, M, S)
#define COS_LOGPAR_IFMM __COS_LOGPAR_X4(I, F, M, M)
#define COS_LOGPAR_IS __COS_LOGPAR_X2(I, S)
#define COS_LOGPAR_ISI __COS_LOGPAR_X3(I, S, I)
#define COS_LOGPAR_ISII __COS_LOGPAR_X4(I, S, I, I)
#define COS_LOGPAR_ISID __COS_LOGPAR_X4(I, S, I, D)
#define COS_LOGPAR_ISIF __COS_LOGPAR_X4(I, S, I, F)
#define COS_LOGPAR_ISIS __COS_LOGPAR_X4(I, S, I, S)
#define COS_LOGPAR_ISIM __COS_LOGPAR_X4(I, S, I, M)
#define COS_LOGPAR_ISD __COS_LOGPAR_X3(I, S, D)
#define COS_LOGPAR_ISDI __COS_LOGPAR_X4(I, S, D, I)
#define COS_LOGPAR_ISDD __COS_LOGPAR_X4(I, S, D, D)
#define COS_LOGPAR_ISDF __COS_LOGPAR_X4(I, S, D, F)
#define COS_LOGPAR_ISDS __COS_LOGPAR_X4(I, S, D, S)
#define COS_LOGPAR_ISDM __COS_LOGPAR_X4(I, S, D, M)
#define COS_LOGPAR_ISF __COS_LOGPAR_X3(I, S, F)
#define COS_LOGPAR_ISFI __COS_LOGPAR_X4(I, S, F, I)
#define COS_LOGPAR_ISFD __COS_LOGPAR_X4(I, S, F, D)
#define COS_LOGPAR_ISFF __COS_LOGPAR_X4(I, S, F, F)
#define COS_LOGPAR_ISFS __COS_LOGPAR_X4(I, S, F, S)
#define COS_LOGPAR_ISFM __COS_LOGPAR_X4(I, S, F, M)
#define COS_LOGPAR_ISS __COS_LOGPAR_X3(I, S, S)
#define COS_LOGPAR_ISSI __COS_LOGPAR_X4(I, S, S, I)
#define COS_LOGPAR_ISSD __COS_LOGPAR_X4(I, S, S, D)
#define COS_LOGPAR_ISSF __COS_LOGPAR_X4(I, S, S, F)
#define COS_LOGPAR_ISSS __COS_LOGPAR_X4(I, S, S, S)
#define COS_LOGPAR_ISSM __COS_LOGPAR_X4(I, S, S, M)
#define COS_LOGPAR_ISM __COS_LOGPAR_X3(I, S, M)
#define COS_LOGPAR_ISMI __COS_LOGPAR_X4(I, S, M, I)
#define COS_LOGPAR_ISMD __COS_LOGPAR_X4(I, S, M, D)
#define COS_LOGPAR_ISMF __COS_LOGPAR_X4(I, S, M, F)
#define COS_LOGPAR_ISMS __COS_LOGPAR_X4(I, S, M, S)
#define COS_LOGPAR_ISMM __COS_LOGPAR_X4(I, S, M, M)
#define COS_LOGPAR_IM __COS_LOGPAR_X2(I, M)
#define COS_LOGPAR_IMI __COS_LOGPAR_X3(I, M, I)
#define COS_LOGPAR_IMII __COS_LOGPAR_X4(I, M, I, I)
#define COS_LOGPAR_IMID __COS_LOGPAR_X4(I, M, I, D)
#define COS_LOGPAR_IMIF __COS_LOGPAR_X4(I, M, I, F)
#define COS_LOGPAR_IMIS __COS_LOGPAR_X4(I, M, I, S)
#define COS_LOGPAR_IMIM __COS_LOGPAR_X4(I, M, I, M)
#define COS_LOGPAR_IMD __COS_LOGPAR_X3(I, M, D)
#define COS_LOGPAR_IMDI __COS_LOGPAR_X4(I, M, D, I)
#define COS_LOGPAR_IMDD __COS_LOGPAR_X4(I, M, D, D)
#define COS_LOGPAR_IMDF __COS_LOGPAR_X4(I, M, D, F)
#define COS_LOGPAR_IMDS __COS_LOGPAR_X4(I, M, D, S)
#define COS_LOGPAR_IMDM __COS_LOGPAR_X4(I, M, D, M)
#define COS_LOGPAR_IMF __COS_LOGPAR_X3(I, M, F)
#define COS_LOGPAR_IMFI __COS_LOGPAR_X4(I, M, F, I)
#define COS_LOGPAR_IMFD __COS_LOGPAR_X4(I, M, F, D)
#define COS_LOGPAR_IMFF __COS_LOGPAR_X4(I, M, F, F)
#define COS_LOGPAR_IMFS __COS_LOGPAR_X4(I, M, F, S)
#define COS_LOGPAR_IMFM __COS_LOGPAR_X4(I, M, F, M)
#define COS_LOGPAR_IMS __COS_LOGPAR_X3(I, M, S)
#define COS_LOGPAR_IMSI __COS_LOGPAR_X4(I, M, S, I)
#define COS_LOGPAR_IMSD __COS_LOGPAR_X4(I, M, S, D)
#define COS_LOGPAR_IMSF __COS_LOGPAR_X4(I, M, S, F)
#define COS_LOGPAR_IMSS __COS_LOGPAR_X4(I, M, S, S)
#define COS_LOGPAR_IMSM __COS_LOGPAR_X4(I, M, S, M)
#define COS_LOGPAR_IMM __COS_LOGPAR_X3(I, M, M)
#define COS_LOGPAR_IMMI __COS_LOGPAR_X4(I, M, M, I)
#define COS_LOGPAR_IMMD __COS_LOGPAR_X4(I, M, M, D)
#define COS_LOGPAR_IMMF __COS_LOGPAR_X4(I, M, M, F)
#define COS_LOGPAR_IMMS __COS_LOGPAR_X4(I, M, M, S)
#define COS_LOGPAR_IMMM __COS_LOGPAR_X4(I, M, M, M)
#define COS_LOGPAR_D __COS_LOGPAR_X1(D)
#define COS_LOGPAR_DI __COS_LOGPAR_X2(D, I)
#define COS_LOGPAR_DII __COS_LOGPAR_X3(D, I, I)
#define COS_LOGPAR_DIII __COS_LOGPAR_X4(D, I, I, I)
#define COS_LOGPAR_DIID __COS_LOGPAR_X4(D, I, I, D)
#define COS_LOGPAR_DIIF __COS_LOGPAR_X4(D, I, I, F)
#define COS_LOGPAR_DIIS __COS_LOGPAR_X4(D, I, I, S)
#define COS_LOGPAR_DIIM __COS_LOGPAR_X4(D, I, I, M)
#define COS_LOGPAR_DID __COS_LOGPAR_X3(D, I, D)
#define COS_LOGPAR_DIDI __COS_LOGPAR_X4(D, I, D, I)
#define COS_LOGPAR_DIDD __COS_LOGPAR_X4(D, I, D, D)
#define COS_LOGPAR_DIDF __COS_LOGPAR_X4(D, I, D, F)
#define COS_LOGPAR_DIDS __COS_LOGPAR_X4(D, I, D, S)
#define COS_LOGPAR_DIDM __COS_LOGPAR_X4(D, I, D, M)
#define COS_LOGPAR_DIF __COS_LOGPAR_X3(D, I, F)
#define COS_LOGPAR_DIFI __COS_LOGPAR_X4(D, I, F, I)
#define COS_LOGPAR_DIFD __COS_LOGPAR_X4(D, I, F, D)
#define COS_LOGPAR_DIFF __COS_LOGPAR_X4(D, I, F, F)
#define COS_LOGPAR_DIFS __COS_LOGPAR_X4(D, I, F, S)
#define COS_LOGPAR_DIFM __COS_LOGPAR_X4(D, I, F, M)
#define COS_LOGPAR_DIS __COS_LOGPAR_X3(D, I, S)
#define COS_LOGPAR_DISI __COS_LOGPAR_X4(D, I, S, I)
#define COS_LOGPAR_DISD __COS_LOGPAR_X4(D, I, S, D)
#define COS_LOGPAR_DISF __COS_LOGPAR_X4(D, I, S, F)
#define COS_LOGPAR_DISS __COS_LOGPAR_X4(D, I, S, S)
#define COS_LOGPAR_DISM __COS_LOGPAR_X4(D, I, S, M)
#define COS_LOGPAR_DIM __COS_LOGPAR_X3(D, I, M)
#define COS_LOGPAR_DIMI __COS_LOGPAR_X4(D, I, M, I)
#define COS_LOGPAR_DIMD __COS_LOGPAR_X4(D, I, M, D)
#define COS_LOGPAR_DIMF __COS_LOGPAR_X4(D, I, M, F)
#define COS_LOGPAR_DIMS __COS_LOGPAR_X4(D, I, M, S)
#define COS_LOGPAR_DIMM __COS_LOGPAR_X4(D, I, M, M)
#define COS_LOGPAR_DD __COS_LOGPAR_X2(D, D)
#define COS_LOGPAR_DDI __COS_LOGPAR_X3(D, D, I)
#define COS_LOGPAR_DDII __COS_LOGPAR_X4(D, D, I, I)
#define COS_LOGPAR_DDID __COS_LOGPAR_X4(D, D, I, D)
#define COS_LOGPAR_DDIF __COS_LOGPAR_X4(D, D, I, F)
#define COS_LOGPAR_DDIS __COS_LOGPAR_X4(D, D, I, S)
#define COS_LOGPAR_DDIM __COS_LOGPAR_X4(D, D, I, M)
#define COS_LOGPAR_DDD __COS_LOGPAR_X3(D, D, D)
#define COS_LOGPAR_DDDI __COS_LOGPAR_X4(D, D, D, I)
#define COS_LOGPAR_DDDD __COS_LOGPAR_X4(D, D, D, D)
#define COS_LOGPAR_DDDF __COS_LOGPAR_X4(D, D, D, F)
#define COS_LOGPAR_DDDS __COS_LOGPAR_X4(D, D, D, S)
#define COS_LOGPAR_DDDM __COS_LOGPAR_X4(D, D, D, M)
#define COS_LOGPAR_DDF __COS_LOGPAR_X3(D, D, F)
#define COS_LOGPAR_DDFI __COS_LOGPAR_X4(D, D, F, I)
#define COS_LOGPAR_DDFD __COS_LOGPAR_X4(D, D, F, D)
#define COS_LOGPAR_DDFF __COS_LOGPAR_X4(D, D, F, F)
#define COS_LOGPAR_DDFS __COS_LOGPAR_X4(D, D, F, S)
#define COS_LOGPAR_DDFM __COS_LOGPAR_X4(D, D, F, M)
#define COS_LOGPAR_DDS __COS_LOGPAR_X3(D, D, S)
#define COS_LOGPAR_DDSI __COS_LOGPAR_X4(D, D, S, I)
#define COS_LOGPAR_DDSD __COS_LOGPAR_X4(D, D, S, D)
#define COS_LOGPAR_DDSF __COS_LOGPAR_X4(D, D, S, F)
#define COS_LOGPAR_DDSS __COS_LOGPAR_X4(D, D, S, S)
#define COS_LOGPAR_DDSM __COS_LOGPAR_X4(D, D, S, M)
#define COS_LOGPAR_DDM __COS_LOGPAR_X3(D, D, M)
#define COS_LOGPAR_DDMI __COS_LOGPAR_X4(D, D, M, I)
#define COS_LOGPAR_DDMD __COS_LOGPAR_X4(D, D, M, D)
#define COS_LOGPAR_DDMF __COS_LOGPAR_X4(D, D, M, F)
#define COS_LOGPAR_DDMS __COS_LOGPAR_X4(D, D, M, S)
#define COS_LOGPAR_DDMM __COS_LOGPAR_X4(D, D, M, M)
#define COS_LOGPAR_DF __COS_LOGPAR_X2(D, F)
#define COS_LOGPAR_DFI __COS_LOGPAR_X3(D, F, I)
#define COS_LOGPAR_DFII __COS_LOGPAR_X4(D, F, I, I)
#define COS_LOGPAR_DFID __COS_LOGPAR_X4(D, F, I, D)
#define COS_LOGPAR_DFIF __COS_LOGPAR_X4(D, F, I, F)
#define COS_LOGPAR_DFIS __COS_LOGPAR_X4(D, F, I, S)
#define COS_LOGPAR_DFIM __COS_LOGPAR_X4(D, F, I, M)
#define COS_LOGPAR_DFD __COS_LOGPAR_X3(D, F, D)
#define COS_LOGPAR_DFDI __COS_LOGPAR_X4(D, F, D, I)
#define COS_LOGPAR_DFDD __COS_LOGPAR_X4(D, F, D, D)
#define COS_LOGPAR_DFDF __COS_LOGPAR_X4(D, F, D, F)
#define COS_LOGPAR_DFDS __COS_LOGPAR_X4(D, F, D, S)
#define COS_LOGPAR_DFDM __COS_LOGPAR_X4(D, F, D, M)
#define COS_LOGPAR_DFF __COS_LOGPAR_X3(D, F, F)
#define COS_LOGPAR_DFFI __COS_LOGPAR_X4(D, F, F, I)
#define COS_LOGPAR_DFFD __COS_LOGPAR_X4(D, F, F, D)
#define COS_LOGPAR_DFFF __COS_LOGPAR_X4(D, F, F, F)
#define COS_LOGPAR_DFFS __COS_LOGPAR_X4(D, F, F, S)
#define COS_LOGPAR_DFFM __COS_LOGPAR_X4(D, F, F, M)
#define COS_LOGPAR_DFS __COS_LOGPAR_X3(D, F, S)
#define COS_LOGPAR_DFSI __COS_LOGPAR_X4(D, F, S, I)
#define COS_LOGPAR_DFSD __COS_LOGPAR_X4(D, F, S, D)
#define COS_LOGPAR_DFSF __COS_LOGPAR_X4(D, F, S, F)
#define COS_LOGPAR_DFSS __COS_LOGPAR_X4(D, F, S, S)
#define COS_LOGPAR_DFSM __COS_LOGPAR_X4(D, F, S, M)
#define COS_LOGPAR_DFM __COS_LOGPAR_X3(D, F, M)
#define COS_LOGPAR_DFMI __COS_LOGPAR_X4(D, F, M, I)
#define COS_LOGPAR_DFMD __COS_LOGPAR_X4(D, F, M, D)
#define COS_LOGPAR_DFMF __COS_LOGPAR_X4(D, F, M, F)
#define COS_LOGPAR_DFMS __COS_LOGPAR_X4(D, F, M, S)
#define COS_LOGPAR_DFMM __COS_LOGPAR_X4(D, F, M, M)
#define COS_LOGPAR_DS __COS_LOGPAR_X2(D, S)
#define COS_LOGPAR_DSI __COS_LOGPAR_X3(D, S, I)
#define COS_LOGPAR_DSII __COS_LOGPAR_X4(D, S, I, I)
#define COS_LOGPAR_DSID __COS_LOGPAR_X4(D, S, I, D)
#define COS_LOGPAR_DSIF __COS_LOGPAR_X4(D, S, I, F)
#define COS_LOGPAR_DSIS __COS_LOGPAR_X4(D, S, I, S)
#define COS_LOGPAR_DSIM __COS_LOGPAR_X4(D, S, I, M)
#define COS_LOGPAR_DSD __COS_LOGPAR_X3(D, S, D)
#define COS_LOGPAR_DSDI __COS_LOGPAR_X4(D, S, D, I)
#define COS_LOGPAR_DSDD __COS_LOGPAR_X4(D, S, D, D)
#define COS_LOGPAR_DSDF __COS_LOGPAR_X4(D, S, D, F)
#define COS_LOGPAR_DSDS __COS_LOGPAR_X4(D, S, D, S)
#define COS_LOGPAR_DSDM __COS_LOGPAR_X4(D, S, D, M)
#define COS_LOGPAR_DSF __COS_LOGPAR_X3(D, S, F)
#define COS_LOGPAR_DSFI __COS_LOGPAR_X4(D, S, F, I)
#define COS_LOGPAR_DSFD __COS_LOGPAR_X4(D, S, F, D)
#define COS_LOGPAR_DSFF __COS_LOGPAR_X4(D, S, F, F)
#define COS_LOGPAR_DSFS __COS_LOGPAR_X4(D, S, F, S)
#define COS_LOGPAR_DSFM __COS_LOGPAR_X4(D, S, F, M)
#define COS_LOGPAR_DSS __COS_LOGPAR_X3(D, S, S)
#define COS_LOGPAR_DSSI __COS_LOGPAR_X4(D, S, S, I)
#define COS_LOGPAR_DSSD __COS_LOGPAR_X4(D, S, S, D)
#define COS_LOGPAR_DSSF __COS_LOGPAR_X4(D, S, S, F)
#define COS_LOGPAR_DSSS __COS_LOGPAR_X4(D, S, S, S)
#define COS_LOGPAR_DSSM __COS_LOGPAR_X4(D, S, S, M)
#define COS_LOGPAR_DSM __COS_LOGPAR_X3(D, S, M)
#define COS_LOGPAR_DSMI __COS_LOGPAR_X4(D, S, M, I)
#define COS_LOGPAR_DSMD __COS_LOGPAR_X4(D, S, M, D)
#define COS_LOGPAR_DSMF __COS_LOGPAR_X4(D, S, M, F)
#define COS_LOGPAR_DSMS __COS_LOGPAR_X4(D, S, M, S)
#define COS_LOGPAR_DSMM __COS_LOGPAR_X4(D, S, M, M)
#define COS_LOGPAR_DM __COS_LOGPAR_X2(D, M)
#define COS_LOGPAR_DMI __COS_LOGPAR_X3(D, M, I)
#define COS_LOGPAR_DMII __COS_LOGPAR_X4(D, M, I, I)
#define COS_LOGPAR_DMID __COS_LOGPAR_X4(D, M, I, D)
#define COS_LOGPAR_DMIF __COS_LOGPAR_X4(D, M, I, F)
#define COS_LOGPAR_DMIS __COS_LOGPAR_X4(D, M, I, S)
#define COS_LOGPAR_DMIM __COS_LOGPAR_X4(D, M, I, M)
#define COS_LOGPAR_DMD __COS_LOGPAR_X3(D, M, D)
#define COS_LOGPAR_DMDI __COS_LOGPAR_X4(D, M, D, I)
#define COS_LOGPAR_DMDD __COS_LOGPAR_X4(D, M, D, D)
#define COS_LOGPAR_DMDF __COS_LOGPAR_X4(D, M, D, F)
#define COS_LOGPAR_DMDS __COS_LOGPAR_X4(D, M, D, S)
#define COS_LOGPAR_DMDM __COS_LOGPAR_X4(D, M, D, M)
#define COS_LOGPAR_DMF __COS_LOGPAR_X3(D, M, F)
#define COS_LOGPAR_DMFI __COS_LOGPAR_X4(D, M, F, I)
#define COS_LOGPAR_DMFD __COS_LOGPAR_X4(D, M, F, D)
#define COS_LOGPAR_DMFF __COS_LOGPAR_X4(D, M, F, F)
#define COS_LOGPAR_DMFS __COS_LOGPAR_X4(D, M, F, S)
#define COS_LOGPAR_DMFM __COS_LOGPAR_X4(D, M, F, M)
#define COS_LOGPAR_DMS __COS_LOGPAR_X3(D, M, S)
#define COS_LOGPAR_DMSI __COS_LOGPAR_X4(D, M, S, I)
#define COS_LOGPAR_DMSD __COS_LOGPAR_X4(D, M, S, D)
#define COS_LOGPAR_DMSF __COS_LOGPAR_X4(D, M, S, F)
#define COS_LOGPAR_DMSS __COS_LOGPAR_X4(D, M, S, S)
#define COS_LOGPAR_DMSM __COS_LOGPAR_X4(D, M, S, M)
#define COS_LOGPAR_DMM __COS_LOGPAR_X3(D, M, M)
#define COS_LOGPAR_DMMI __COS_LOGPAR_X4(D, M, M, I)
#define COS_LOGPAR_DMMD __COS_LOGPAR_X4(D, M, M, D)
#define COS_LOGPAR_DMMF __COS_LOGPAR_X4(D, M, M, F)
#define COS_LOGPAR_DMMS __COS_LOGPAR_X4(D, M, M, S)
#define COS_LOGPAR_DMMM __COS_LOGPAR_X4(D, M, M, M)
#define COS_LOGPAR_F __COS_LOGPAR_X1(F)
#define COS_LOGPAR_FI __COS_LOGPAR_X2(F, I)
#define COS_LOGPAR_FII __COS_LOGPAR_X3(F, I, I)
#define COS_LOGPAR_FIII __COS_LOGPAR_X4(F, I, I, I)
#define COS_LOGPAR_FIID __COS_LOGPAR_X4(F, I, I, D)
#define COS_LOGPAR_FIIF __COS_LOGPAR_X4(F, I, I, F)
#define COS_LOGPAR_FIIS __COS_LOGPAR_X4(F, I, I, S)
#define COS_LOGPAR_FIIM __COS_LOGPAR_X4(F, I, I, M)
#define COS_LOGPAR_FID __COS_LOGPAR_X3(F, I, D)
#define COS_LOGPAR_FIDI __COS_LOGPAR_X4(F, I, D, I)
#define COS_LOGPAR_FIDD __COS_LOGPAR_X4(F, I, D, D)
#define COS_LOGPAR_FIDF __COS_LOGPAR_X4(F, I, D, F)
#define COS_LOGPAR_FIDS __COS_LOGPAR_X4(F, I, D, S)
#define COS_LOGPAR_FIDM __COS_LOGPAR_X4(F, I, D, M)
#define COS_LOGPAR_FIF __COS_LOGPAR_X3(F, I, F)
#define COS_LOGPAR_FIFI __COS_LOGPAR_X4(F, I, F, I)
#define COS_LOGPAR_FIFD __COS_LOGPAR_X4(F, I, F, D)
#define COS_LOGPAR_FIFF __COS_LOGPAR_X4(F, I, F, F)
#define COS_LOGPAR_FIFS __COS_LOGPAR_X4(F, I, F, S)
#define COS_LOGPAR_FIFM __COS_LOGPAR_X4(F, I, F, M)
#define COS_LOGPAR_FIS __COS_LOGPAR_X3(F, I, S)
#define COS_LOGPAR_FISI __COS_LOGPAR_X4(F, I, S, I)
#define COS_LOGPAR_FISD __COS_LOGPAR_X4(F, I, S, D)
#define COS_LOGPAR_FISF __COS_LOGPAR_X4(F, I, S, F)
#define COS_LOGPAR_FISS __COS_LOGPAR_X4(F, I, S, S)
#define COS_LOGPAR_FISM __COS_LOGPAR_X4(F, I, S, M)
#define COS_LOGPAR_FIM __COS_LOGPAR_X3(F, I, M)
#define COS_LOGPAR_FIMI __COS_LOGPAR_X4(F, I, M, I)
#define COS_LOGPAR_FIMD __COS_LOGPAR_X4(F, I, M, D)
#define COS_LOGPAR_FIMF __COS_LOGPAR_X4(F, I, M, F)
#define COS_LOGPAR_FIMS __COS_LOGPAR_X4(F, I, M, S)
#define COS_LOGPAR_FIMM __COS_LOGPAR_X4(F, I, M, M)
#define COS_LOGPAR_FD __COS_LOGPAR_X2(F, D)
#define COS_LOGPAR_FDI __COS_LOGPAR_X3(F, D, I)
#define COS_LOGPAR_FDII __COS_LOGPAR_X4(F, D, I, I)
#define COS_LOGPAR_FDID __COS_LOGPAR_X4(F, D, I, D)
#define COS_LOGPAR_FDIF __COS_LOGPAR_X4(F, D, I, F)
#define COS_LOGPAR_FDIS __COS_LOGPAR_X4(F, D, I, S)
#define COS_LOGPAR_FDIM __COS_LOGPAR_X4(F, D, I, M)
#define COS_LOGPAR_FDD __COS_LOGPAR_X3(F, D, D)
#define COS_LOGPAR_FDDI __COS_LOGPAR_X4(F, D, D, I)
#define COS_LOGPAR_FDDD __COS_LOGPAR_X4(F, D, D, D)
#define COS_LOGPAR_FDDF __COS_LOGPAR_X4(F, D, D, F)
#define COS_LOGPAR_FDDS __COS_LOGPAR_X4(F, D, D, S)
#define COS_LOGPAR_FDDM __COS_LOGPAR_X4(F, D, D, M)
#define COS_LOGPAR_FDF __COS_LOGPAR_X3(F, D, F)
#define COS_LOGPAR_FDFI __COS_LOGPAR_X4(F, D, F, I)
#define COS_LOGPAR_FDFD __COS_LOGPAR_X4(F, D, F, D)
#define COS_LOGPAR_FDFF __COS_LOGPAR_X4(F, D, F, F)
#define COS_LOGPAR_FDFS __COS_LOGPAR_X4(F, D, F, S)
#define COS_LOGPAR_FDFM __COS_LOGPAR_X4(F, D, F, M)
#define COS_LOGPAR_FDS __COS_LOGPAR_X3(F, D, S)
#define COS_LOGPAR_FDSI __COS_LOGPAR_X4(F, D, S, I)
#define COS_LOGPAR_FDSD __COS_LOGPAR_X4(F, D, S, D)
#define COS_LOGPAR_FDSF __COS_LOGPAR_X4(F, D, S, F)
#define COS_LOGPAR_FDSS __COS_LOGPAR_X4(F, D, S, S)
#define COS_LOGPAR_FDSM __COS_LOGPAR_X4(F, D, S, M)
#define COS_LOGPAR_FDM __COS_LOGPAR_X3(F, D, M)
#define COS_LOGPAR_FDMI __COS_LOGPAR_X4(F, D, M, I)
#define COS_LOGPAR_FDMD __COS_LOGPAR_X4(F, D, M, D)
#define COS_LOGPAR_FDMF __COS_LOGPAR_X4(F, D, M, F)
#define COS_LOGPAR_FDMS __COS_LOGPAR_X4(F, D, M, S)
#define COS_LOGPAR_FDMM __COS_LOGPAR_X4(F, D, M, M)
#define COS_LOGPAR_FF __COS_LOGPAR_X2(F, F)
#define COS_LOGPAR_FFI __COS_LOGPAR_X3(F, F, I)
#define COS_LOGPAR_FFII __COS_LOGPAR_X4(F, F, I, I)
#define COS_LOGPAR_FFID __COS_LOGPAR_X4(F, F, I, D)
#define COS_LOGPAR_FFIF __COS_LOGPAR_X4(F, F, I, F)
#define COS_LOGPAR_FFIS __COS_LOGPAR_X4(F, F, I, S)
#define COS_LOGPAR_FFIM __COS_LOGPAR_X4(F, F, I, M)
#define COS_LOGPAR_FFD __COS_LOGPAR_X3(F, F, D)
#define COS_LOGPAR_FFDI __COS_LOGPAR_X4(F, F, D, I)
#define COS_LOGPAR_FFDD __COS_LOGPAR_X4(F, F, D, D)
#define COS_LOGPAR_FFDF __COS_LOGPAR_X4(F, F, D, F)
#define COS_LOGPAR_FFDS __COS_LOGPAR_X4(F, F, D, S)
#define COS_LOGPAR_FFDM __COS_LOGPAR_X4(F, F, D, M)
#define COS_LOGPAR_FFF __COS_LOGPAR_X3(F, F, F)
#define COS_LOGPAR_FFFI __COS_LOGPAR_X4(F, F, F, I)
#define COS_LOGPAR_FFFD __COS_LOGPAR_X4(F, F, F, D)
#define COS_LOGPAR_FFFF __COS_LOGPAR_X4(F, F, F, F)
#define COS_LOGPAR_FFFS __COS_LOGPAR_X4(F, F, F, S)
#define COS_LOGPAR_FFFM __COS_LOGPAR_X4(F, F, F, M)
#define COS_LOGPAR_FFS __COS_LOGPAR_X3(F, F, S)
#define COS_LOGPAR_FFSI __COS_LOGPAR_X4(F, F, S, I)
#define COS_LOGPAR_FFSD __COS_LOGPAR_X4(F, F, S, D)
#define COS_LOGPAR_FFSF __COS_LOGPAR_X4(F, F, S, F)
#define COS_LOGPAR_FFSS __COS_LOGPAR_X4(F, F, S, S)
#define COS_LOGPAR_FFSM __COS_LOGPAR_X4(F, F, S, M)
#define COS_LOGPAR_FFM __COS_LOGPAR_X3(F, F, M)
#define COS_LOGPAR_FFMI __COS_LOGPAR_X4(F, F, M, I)
#define COS_LOGPAR_FFMD __COS_LOGPAR_X4(F, F, M, D)
#define COS_LOGPAR_FFMF __COS_LOGPAR_X4(F, F, M, F)
#define COS_LOGPAR_FFMS __COS_LOGPAR_X4(F, F, M, S)
#define COS_LOGPAR_FFMM __COS_LOGPAR_X4(F, F, M, M)
#define COS_LOGPAR_FS __COS_LOGPAR_X2(F, S)
#define COS_LOGPAR_FSI __COS_LOGPAR_X3(F, S, I)
#define COS_LOGPAR_FSII __COS_LOGPAR_X4(F, S, I, I)
#define COS_LOGPAR_FSID __COS_LOGPAR_X4(F, S, I, D)
#define COS_LOGPAR_FSIF __COS_LOGPAR_X4(F, S, I, F)
#define COS_LOGPAR_FSIS __COS_LOGPAR_X4(F, S, I, S)
#define COS_LOGPAR_FSIM __COS_LOGPAR_X4(F, S, I, M)
#define COS_LOGPAR_FSD __COS_LOGPAR_X3(F, S, D)
#define COS_LOGPAR_FSDI __COS_LOGPAR_X4(F, S, D, I)
#define COS_LOGPAR_FSDD __COS_LOGPAR_X4(F, S, D, D)
#define COS_LOGPAR_FSDF __COS_LOGPAR_X4(F, S, D, F)
#define COS_LOGPAR_FSDS __COS_LOGPAR_X4(F, S, D, S)
#define COS_LOGPAR_FSDM __COS_LOGPAR_X4(F, S, D, M)
#define COS_LOGPAR_FSF __COS_LOGPAR_X3(F, S, F)
#define COS_LOGPAR_FSFI __COS_LOGPAR_X4(F, S, F, I)
#define COS_LOGPAR_FSFD __COS_LOGPAR_X4(F, S, F, D)
#define COS_LOGPAR_FSFF __COS_LOGPAR_X4(F, S, F, F)
#define COS_LOGPAR_FSFS __COS_LOGPAR_X4(F, S, F, S)
#define COS_LOGPAR_FSFM __COS_LOGPAR_X4(F, S, F, M)
#define COS_LOGPAR_FSS __COS_LOGPAR_X3(F, S, S)
#define COS_LOGPAR_FSSI __COS_LOGPAR_X4(F, S, S, I)
#define COS_LOGPAR_FSSD __COS_LOGPAR_X4(F, S, S, D)
#define COS_LOGPAR_FSSF __COS_LOGPAR_X4(F, S, S, F)
#define COS_LOGPAR_FSSS __COS_LOGPAR_X4(F, S, S, S)
#define COS_LOGPAR_FSSM __COS_LOGPAR_X4(F, S, S, M)
#define COS_LOGPAR_FSM __COS_LOGPAR_X3(F, S, M)
#define COS_LOGPAR_FSMI __COS_LOGPAR_X4(F, S, M, I)
#define COS_LOGPAR_FSMD __COS_LOGPAR_X4(F, S, M, D)
#define COS_LOGPAR_FSMF __COS_LOGPAR_X4(F, S, M, F)
#define COS_LOGPAR_FSMS __COS_LOGPAR_X4(F, S, M, S)
#define COS_LOGPAR_FSMM __COS_LOGPAR_X4(F, S, M, M)
#define COS_LOGPAR_FM __COS_LOGPAR_X2(F, M)
#define COS_LOGPAR_FMI __COS_LOGPAR_X3(F, M, I)
#define COS_LOGPAR_FMII __COS_LOGPAR_X4(F, M, I, I)
#define COS_LOGPAR_FMID __COS_LOGPAR_X4(F, M, I, D)
#define COS_LOGPAR_FMIF __COS_LOGPAR_X4(F, M, I, F)
#define COS_LOGPAR_FMIS __COS_LOGPAR_X4(F, M, I, S)
#define COS_LOGPAR_FMIM __COS_LOGPAR_X4(F, M, I, M)
#define COS_LOGPAR_FMD __COS_LOGPAR_X3(F, M, D)
#define COS_LOGPAR_FMDI __COS_LOGPAR_X4(F, M, D, I)
#define COS_LOGPAR_FMDD __COS_LOGPAR_X4(F, M, D, D)
#define COS_LOGPAR_FMDF __COS_LOGPAR_X4(F, M, D, F)
#define COS_LOGPAR_FMDS __COS_LOGPAR_X4(F, M, D, S)
#define COS_LOGPAR_FMDM __COS_LOGPAR_X4(F, M, D, M)
#define COS_LOGPAR_FMF __COS_LOGPAR_X3(F, M, F)
#define COS_LOGPAR_FMFI __COS_LOGPAR_X4(F, M, F, I)
#define COS_LOGPAR_FMFD __COS_LOGPAR_X4(F, M, F, D)
#define COS_LOGPAR_FMFF __COS_LOGPAR_X4(F, M, F, F)
#define COS_LOGPAR_FMFS __COS_LOGPAR_X4(F, M, F, S)
#define COS_LOGPAR_FMFM __COS_LOGPAR_X4(F, M, F, M)
#define COS_LOGPAR_FMS __COS_LOGPAR_X3(F, M, S)
#define COS_LOGPAR_FMSI __COS_LOGPAR_X4(F, M, S, I)
#define COS_LOGPAR_FMSD __COS_LOGPAR_X4(F, M, S, D)
#define COS_LOGPAR_FMSF __COS_LOGPAR_X4(F, M, S, F)
#define COS_LOGPAR_FMSS __COS_LOGPAR_X4(F, M, S, S)
#define COS_LOGPAR_FMSM __COS_LOGPAR_X4(F, M, S, M)
#define COS_LOGPAR_FMM __COS_LOGPAR_X3(F, M, M)
#define COS_LOGPAR_FMMI __COS_LOGPAR_X4(F, M, M, I)
#define COS_LOGPAR_FMMD __COS_LOGPAR_X4(F, M, M, D)
#define COS_LOGPAR_FMMF __COS_LOGPAR_X4(F, M, M, F)
#define COS_LOGPAR_FMMS __COS_LOGPAR_X4(F, M, M, S)
#define COS_LOGPAR_FMMM __COS_LOGPAR_X4(F, M, M, M)
#define COS_LOGPAR_S __COS_LOGPAR_X1(S)
#define COS_LOGPAR_SI __COS_LOGPAR_X2(S, I)
#define COS_LOGPAR_SII __COS_LOGPAR_X3(S, I, I)
#define COS_LOGPAR_SIII __COS_LOGPAR_X4(S, I, I, I)
#define COS_LOGPAR_SIID __COS_LOGPAR_X4(S, I, I, D)
#define COS_LOGPAR_SIIF __COS_LOGPAR_X4(S, I, I, F)
#define COS_LOGPAR_SIIS __COS_LOGPAR_X4(S, I, I, S)
#define COS_LOGPAR_SIIM __COS_LOGPAR_X4(S, I, I, M)
#define COS_LOGPAR_SID __COS_LOGPAR_X3(S, I, D)
#define COS_LOGPAR_SIDI __COS_LOGPAR_X4(S, I, D, I)
#define COS_LOGPAR_SIDD __COS_LOGPAR_X4(S, I, D, D)
#define COS_LOGPAR_SIDF __COS_LOGPAR_X4(S, I, D, F)
#define COS_LOGPAR_SIDS __COS_LOGPAR_X4(S, I, D, S)
#define COS_LOGPAR_SIDM __COS_LOGPAR_X4(S, I, D, M)
#define COS_LOGPAR_SIF __COS_LOGPAR_X3(S, I, F)
#define COS_LOGPAR_SIFI __COS_LOGPAR_X4(S, I, F, I)
#define COS_LOGPAR_SIFD __COS_LOGPAR_X4(S, I, F, D)
#define COS_LOGPAR_SIFF __COS_LOGPAR_X4(S, I, F, F)
#define COS_LOGPAR_SIFS __COS_LOGPAR_X4(S, I, F, S)
#define COS_LOGPAR_SIFM __COS_LOGPAR_X4(S, I, F, M)
#define COS_LOGPAR_SIS __COS_LOGPAR_X3(S, I, S)
#define COS_LOGPAR_SISI __COS_LOGPAR_X4(S, I, S, I)
#define COS_LOGPAR_SISD __COS_LOGPAR_X4(S, I, S, D)
#define COS_LOGPAR_SISF __COS_LOGPAR_X4(S, I, S, F)
#define COS_LOGPAR_SISS __COS_LOGPAR_X4(S, I, S, S)
#define COS_LOGPAR_SISM __COS_LOGPAR_X4(S, I, S, M)
#define COS_LOGPAR_SIM __COS_LOGPAR_X3(S, I, M)
#define COS_LOGPAR_SIMI __COS_LOGPAR_X4(S, I, M, I)
#define COS_LOGPAR_SIMD __COS_LOGPAR_X4(S, I, M, D)
#define COS_LOGPAR_SIMF __COS_LOGPAR_X4(S, I, M, F)
#define COS_LOGPAR_SIMS __COS_LOGPAR_X4(S, I, M, S)
#define COS_LOGPAR_SIMM __COS_LOGPAR_X4(S, I, M, M)
#define COS_LOGPAR_SD __COS_LOGPAR_X2(S, D)
#define COS_LOGPAR_SDI __COS_LOGPAR_X3(S, D, I)
#define COS_LOGPAR_SDII __COS_LOGPAR_X4(S, D, I, I)
#define COS_LOGPAR_SDID __COS_LOGPAR_X4(S, D, I, D)
#define COS_LOGPAR_SDIF __COS_LOGPAR_X4(S, D, I, F)
#define COS_LOGPAR_SDIS __COS_LOGPAR_X4(S, D, I, S)
#define COS_LOGPAR_SDIM __COS_LOGPAR_X4(S, D, I, M)
#define COS_LOGPAR_SDD __COS_LOGPAR_X3(S, D, D)
#define COS_LOGPAR_SDDI __COS_LOGPAR_X4(S, D, D, I)
#define COS_LOGPAR_SDDD __COS_LOGPAR_X4(S, D, D, D)
#define COS_LOGPAR_SDDF __COS_LOGPAR_X4(S, D, D, F)
#define COS_LOGPAR_SDDS __COS_LOGPAR_X4(S, D, D, S)
#define COS_LOGPAR_SDDM __COS_LOGPAR_X4(S, D, D, M)
#define COS_LOGPAR_SDF __COS_LOGPAR_X3(S, D, F)
#define COS_LOGPAR_SDFI __COS_LOGPAR_X4(S, D, F, I)
#define COS_LOGPAR_SDFD __COS_LOGPAR_X4(S, D, F, D)
#define COS_LOGPAR_SDFF __COS_LOGPAR_X4(S, D, F, F)
#define COS_LOGPAR_SDFS __COS_LOGPAR_X4(S, D, F, S)
#define COS_LOGPAR_SDFM __COS_LOGPAR_X4(S, D, F, M)
#define COS_LOGPAR_SDS __COS_LOGPAR_X3(S, D, S)
#define COS_LOGPAR_SDSI __COS_LOGPAR_X4(S, D, S, I)
#define COS_LOGPAR_SDSD __COS_LOGPAR_X4(S, D, S, D)
#define COS_LOGPAR_SDSF __COS_LOGPAR_X4(S, D, S, F)
#define COS_LOGPAR_SDSS __COS_LOGPAR_X4(S, D, S, S)
#define COS_LOGPAR_SDSM __COS_LOGPAR_X4(S, D, S, M)
#define COS_LOGPAR_SDM __COS_LOGPAR_X3(S, D, M)
#define COS_LOGPAR_SDMI __COS_LOGPAR_X4(S, D, M, I)
#define COS_LOGPAR_SDMD __COS_LOGPAR_X4(S, D, M, D)
#define COS_LOGPAR_SDMF __COS_LOGPAR_X4(S, D, M, F)
#define COS_LOGPAR_SDMS __COS_LOGPAR_X4(S, D, M, S)
#define COS_LOGPAR_SDMM __COS_LOGPAR_X4(S, D, M, M)
#define COS_LOGPAR_SF __COS_LOGPAR_X2(S, F)
#define COS_LOGPAR_SFI __COS_LOGPAR_X3(S, F, I)
#define COS_LOGPAR_SFII __COS_LOGPAR_X4(S, F, I, I)
#define COS_LOGPAR_SFID __COS_LOGPAR_X4(S, F, I, D)
#define COS_LOGPAR_SFIF __COS_LOGPAR_X4(S, F, I, F)
#define COS_LOGPAR_SFIS __COS_LOGPAR_X4(S, F, I, S)
#define COS_LOGPAR_SFIM __COS_LOGPAR_X4(S, F, I, M)
#define COS_LOGPAR_SFD __COS_LOGPAR_X3(S, F, D)
#define COS_LOGPAR_SFDI __COS_LOGPAR_X4(S, F, D, I)
#define COS_LOGPAR_SFDD __COS_LOGPAR_X4(S, F, D, D)
#define COS_LOGPAR_SFDF __COS_LOGPAR_X4(S, F, D, F)
#define COS_LOGPAR_SFDS __COS_LOGPAR_X4(S, F, D, S)
#define COS_LOGPAR_SFDM __COS_LOGPAR_X4(S, F, D, M)
#define COS_LOGPAR_SFF __COS_LOGPAR_X3(S, F, F)
#define COS_LOGPAR_SFFI __COS_LOGPAR_X4(S, F, F, I)
#define COS_LOGPAR_SFFD __COS_LOGPAR_X4(S, F, F, D)
#define COS_LOGPAR_SFFF __COS_LOGPAR_X4(S, F, F, F)
#define COS_LOGPAR_SFFS __COS_LOGPAR_X4(S, F, F, S)
#define COS_LOGPAR_SFFM __COS_LOGPAR_X4(S, F, F, M)
#define COS_LOGPAR_SFS __COS_LOGPAR_X3(S, F, S)
#define COS_LOGPAR_SFSI __COS_LOGPAR_X4(S, F, S, I)
#define COS_LOGPAR_SFSD __COS_LOGPAR_X4(S, F, S, D)
#define COS_LOGPAR_SFSF __COS_LOGPAR_X4(S, F, S, F)
#define COS_LOGPAR_SFSS __COS_LOGPAR_X4(S, F, S, S)
#define COS_LOGPAR_SFSM __COS_LOGPAR_X4(S, F, S, M)
#define COS_LOGPAR_SFM __COS_LOGPAR_X3(S, F, M)
#define COS_LOGPAR_SFMI __COS_LOGPAR_X4(S, F, M, I)
#define COS_LOGPAR_SFMD __COS_LOGPAR_X4(S, F, M, D)
#define COS_LOGPAR_SFMF __COS_LOGPAR_X4(S, F, M, F)
#define COS_LOGPAR_SFMS __COS_LOGPAR_X4(S, F, M, S)
#define COS_LOGPAR_SFMM __COS_LOGPAR_X4(S, F, M, M)
#define COS_LOGPAR_SS __COS_LOGPAR_X2(S, S)
#define COS_LOGPAR_SSI __COS_LOGPAR_X3(S, S, I)
#define COS_LOGPAR_SSII __COS_LOGPAR_X4(S, S, I, I)
#define COS_LOGPAR_SSID __COS_LOGPAR_X4(S, S, I, D)
#define COS_LOGPAR_SSIF __COS_LOGPAR_X4(S, S, I, F)
#define COS_LOGPAR_SSIS __COS_LOGPAR_X4(S, S, I, S)
#define COS_LOGPAR_SSIM __COS_LOGPAR_X4(S, S, I, M)
#define COS_LOGPAR_SSD __COS_LOGPAR_X3(S, S, D)
#define COS_LOGPAR_SSDI __COS_LOGPAR_X4(S, S, D, I)
#define COS_LOGPAR_SSDD __COS_LOGPAR_X4(S, S, D, D)
#define COS_LOGPAR_SSDF __COS_LOGPAR_X4(S, S, D, F)
#define COS_LOGPAR_SSDS __COS_LOGPAR_X4(S, S, D, S)
#define COS_LOGPAR_SSDM __COS_LOGPAR_X4(S, S, D, M)
#define COS_LOGPAR_SSF __COS_LOGPAR_X3(S, S, F)
#define COS_LOGPAR_SSFI __COS_LOGPAR_X4(S, S, F, I)
#define COS_LOGPAR_SSFD __COS_LOGPAR_X4(S, S, F, D)
#define COS_LOGPAR_SSFF __COS_LOGPAR_X4(S, S, F, F)
#define COS_LOGPAR_SSFS __COS_LOGPAR_X4(S, S, F, S)
#define COS_LOGPAR_SSFM __COS_LOGPAR_X4(S, S, F, M)
#define COS_LOGPAR_SSS __COS_LOGPAR_X3(S, S, S)
#define COS_LOGPAR_SSSI __COS_LOGPAR_X4(S, S, S, I)
#define COS_LOGPAR_SSSD __COS_LOGPAR_X4(S, S, S, D)
#define COS_LOGPAR_SSSF __COS_LOGPAR_X4(S, S, S, F)
#define COS_LOGPAR_SSSS __COS_LOGPAR_X4(S, S, S, S)
#define COS_LOGPAR_SSSM __COS_LOGPAR_X4(S, S, S, M)
#define COS_LOGPAR_SSM __COS_LOGPAR_X3(S, S, M)
#define COS_LOGPAR_SSMI __COS_LOGPAR_X4(S, S, M, I)
#define COS_LOGPAR_SSMD __COS_LOGPAR_X4(S, S, M, D)
#define COS_LOGPAR_SSMF __COS_LOGPAR_X4(S, S, M, F)
#define COS_LOGPAR_SSMS __COS_LOGPAR_X4(S, S, M, S)
#define COS_LOGPAR_SSMM __COS_LOGPAR_X4(S, S, M, M)
#define COS_LOGPAR_SM __COS_LOGPAR_X2(S, M)
#define COS_LOGPAR_SMI __COS_LOGPAR_X3(S, M, I)
#define COS_LOGPAR_SMII __COS_LOGPAR_X4(S, M, I, I)
#define COS_LOGPAR_SMID __COS_LOGPAR_X4(S, M, I, D)
#define COS_LOGPAR_SMIF __COS_LOGPAR_X4(S, M, I, F)
#define COS_LOGPAR_SMIS __COS_LOGPAR_X4(S, M, I, S)
#define COS_LOGPAR_SMIM __COS_LOGPAR_X4(S, M, I, M)
#define COS_LOGPAR_SMD __COS_LOGPAR_X3(S, M, D)
#define COS_LOGPAR_SMDI __COS_LOGPAR_X4(S, M, D, I)
#define COS_LOGPAR_SMDD __COS_LOGPAR_X4(S, M, D, D)
#define COS_LOGPAR_SMDF __COS_LOGPAR_X4(S, M, D, F)
#define COS_LOGPAR_SMDS __COS_LOGPAR_X4(S, M, D, S)
#define COS_LOGPAR_SMDM __COS_LOGPAR_X4(S, M, D, M)
#define COS_LOGPAR_SMF __COS_LOGPAR_X3(S, M, F)
#define COS_LOGPAR_SMFI __COS_LOGPAR_X4(S, M, F, I)
#define COS_LOGPAR_SMFD __COS_LOGPAR_X4(S, M, F, D)
#define COS_LOGPAR_SMFF __COS_LOGPAR_X4(S, M, F, F)
#define COS_LOGPAR_SMFS __COS_LOGPAR_X4(S, M, F, S)
#define COS_LOGPAR_SMFM __COS_LOGPAR_X4(S, M, F, M)
#define COS_LOGPAR_SMS __COS_LOGPAR_X3(S, M, S)
#define COS_LOGPAR_SMSI __COS_LOGPAR_X4(S, M, S, I)
#define COS_LOGPAR_SMSD __COS_LOGPAR_X4(S, M, S, D)
#define COS_LOGPAR_SMSF __COS_LOGPAR_X4(S, M, S, F)
#define COS_LOGPAR_SMSS __COS_LOGPAR_X4(S, M, S, S)
#define COS_LOGPAR_SMSM __COS_LOGPAR_X4(S, M, S, M)
#define COS_LOGPAR_SMM __COS_LOGPAR_X3(S, M, M)
#define COS_LOGPAR_SMMI __COS_LOGPAR_X4(S, M, M, I)
#define COS_LOGPAR_SMMD __COS_LOGPAR_X4(S, M, M, D)
#define COS_LOGPAR_SMMF __COS_LOGPAR_X4(S, M, M, F)
#define COS_LOGPAR_SMMS __COS_LOGPAR_X4(S, M, M, S)
#define COS_LOGPAR_SMMM __COS_LOGPAR_X4(S, M, M, M)
#define COS_LOGPAR_M __COS_LOGPAR_X1(M)
#define COS_LOGPAR_MI __COS_LOGPAR_X2(M, I)
#define COS_LOGPAR_MII __COS_LOGPAR_X3(M, I, I)
#define COS_LOGPAR_MIII __COS_LOGPAR_X4(M, I, I, I)
#define COS_LOGPAR_MIID __COS_LOGPAR_X4(M, I, I, D)
#define COS_LOGPAR_MIIF __COS_LOGPAR_X4(M, I, I, F)
#define COS_LOGPAR_MIIS __COS_LOGPAR_X4(M, I, I, S)
#define COS_LOGPAR_MIIM __COS_LOGPAR_X4(M, I, I, M)
#define COS_LOGPAR_MID __COS_LOGPAR_X3(M, I, D)
#define COS_LOGPAR_MIDI __COS_LOGPAR_X4(M, I, D, I)
#define COS_LOGPAR_MIDD __COS_LOGPAR_X4(M, I, D, D)
#define COS_LOGPAR_MIDF __COS_LOGPAR_X4(M, I, D, F)
#define COS_LOGPAR_MIDS __COS_LOGPAR_X4(M, I, D, S)
#define COS_LOGPAR_MIDM __COS_LOGPAR_X4(M, I, D, M)
#define COS_LOGPAR_MIF __COS_LOGPAR_X3(M, I, F)
#define COS_LOGPAR_MIFI __COS_LOGPAR_X4(M, I, F, I)
#define COS_LOGPAR_MIFD __COS_LOGPAR_X4(M, I, F, D)
#define COS_LOGPAR_MIFF __COS_LOGPAR_X4(M, I, F, F)
#define COS_LOGPAR_MIFS __COS_LOGPAR_X4(M, I, F, S)
#define COS_LOGPAR_MIFM __COS_LOGPAR_X4(M, I, F, M)
#define COS_LOGPAR_MIS __COS_LOGPAR_X3(M, I, S)
#define COS_LOGPAR_MISI __COS_LOGPAR_X4(M, I, S, I)
#define COS_LOGPAR_MISD __COS_LOGPAR_X4(M, I, S, D)
#define COS_LOGPAR_MISF __COS_LOGPAR_X4(M, I, S, F)
#define COS_LOGPAR_MISS __COS_LOGPAR_X4(M, I, S, S)
#define COS_LOGPAR_MISM __COS_LOGPAR_X4(M, I, S, M)
#define COS_LOGPAR_MIM __COS_LOGPAR_X3(M, I, M)
#define COS_LOGPAR_MIMI __COS_LOGPAR_X4(M, I, M, I)
#define COS_LOGPAR_MIMD __COS_LOGPAR_X4(M, I, M, D)
#define COS_LOGPAR_MIMF __COS_LOGPAR_X4(M, I, M, F)
#define COS_LOGPAR_MIMS __COS_LOGPAR_X4(M, I, M, S)
#define COS_LOGPAR_MIMM __COS_LOGPAR_X4(M, I, M, M)
#define COS_LOGPAR_MD __COS_LOGPAR_X2(M, D)
#define COS_LOGPAR_MDI __COS_LOGPAR_X3(M, D, I)
#define COS_LOGPAR_MDII __COS_LOGPAR_X4(M, D, I, I)
#define COS_LOGPAR_MDID __COS_LOGPAR_X4(M, D, I, D)
#define COS_LOGPAR_MDIF __COS_LOGPAR_X4(M, D, I, F)
#define COS_LOGPAR_MDIS __COS_LOGPAR_X4(M, D, I, S)
#define COS_LOGPAR_MDIM __COS_LOGPAR_X4(M, D, I, M)
#define COS_LOGPAR_MDD __COS_LOGPAR_X3(M, D, D)
#define COS_LOGPAR_MDDI __COS_LOGPAR_X4(M, D, D, I)
#define COS_LOGPAR_MDDD __COS_LOGPAR_X4(M, D, D, D)
#define COS_LOGPAR_MDDF __COS_LOGPAR_X4(M, D, D, F)
#define COS_LOGPAR_MDDS __COS_LOGPAR_X4(M, D, D, S)
#define COS_LOGPAR_MDDM __COS_LOGPAR_X4(M, D, D, M)
#define COS_LOGPAR_MDF __COS_LOGPAR_X3(M, D, F)
#define COS_LOGPAR_MDFI __COS_LOGPAR_X4(M, D, F, I)
#define COS_LOGPAR_MDFD __COS_LOGPAR_X4(M, D, F, D)
#define COS_LOGPAR_MDFF __COS_LOGPAR_X4(M, D, F, F)
#define COS_LOGPAR_MDFS __COS_LOGPAR_X4(M, D, F, S)
#define COS_LOGPAR_MDFM __COS_LOGPAR_X4(M, D, F, M)
#define COS_LOGPAR_MDS __COS_LOGPAR_X3(M, D, S)
#define COS_LOGPAR_MDSI __COS_LOGPAR_X4(M, D, S, I)
#define COS_LOGPAR_MDSD __COS_LOGPAR_X4(M, D, S, D)
#define COS_LOGPAR_MDSF __COS_LOGPAR_X4(M, D, S, F)
#define COS_LOGPAR_MDSS __COS_LOGPAR_X4(M, D, S, S)
#define COS_LOGPAR_MDSM __COS_LOGPAR_X4(M, D, S, M)
#define COS_LOGPAR_MDM __COS_LOGPAR_X3(M, D, M)
#define COS_LOGPAR_MDMI __COS_LOGPAR_X4(M, D, M, I)
#define COS_LOGPAR_MDMD __COS_LOGPAR_X4(M, D, M, D)
#define COS_LOGPAR_MDMF __COS_LOGPAR_X4(M, D, M, F)
#define COS_LOGPAR_MDMS __COS_LOGPAR_X4(M, D, M, S)
#define COS_LOGPAR_MDMM __COS_LOGPAR_X4(M, D, M, M)
#define COS_LOGPAR_MF __COS_LOGPAR_X2(M, F)
#define COS_LOGPAR_MFI __COS_LOGPAR_X3(M, F, I)
#define COS_LOGPAR_MFII __COS_LOGPAR_X4(M, F, I, I)
#define COS_LOGPAR_MFID __COS_LOGPAR_X4(M, F, I, D)
#define COS_LOGPAR_MFIF __COS_LOGPAR_X4(M, F, I, F)
#define COS_LOGPAR_MFIS __COS_LOGPAR_X4(M, F, I, S)
#define COS_LOGPAR_MFIM __COS_LOGPAR_X4(M, F, I, M)
#define COS_LOGPAR_MFD __COS_LOGPAR_X3(M, F, D)
#define COS_LOGPAR_MFDI __COS_LOGPAR_X4(M, F, D, I)
#define COS_LOGPAR_MFDD __COS_LOGPAR_X4(M, F, D, D)
#define COS_LOGPAR_MFDF __COS_LOGPAR_X4(M, F, D, F)
#define COS_LOGPAR_MFDS __COS_LOGPAR_X4(M, F, D, S)
#define COS_LOGPAR_MFDM __COS_LOGPAR_X4(M, F, D, M)
#define COS_LOGPAR_MFF __COS_LOGPAR_X3(M, F, F)
#define COS_LOGPAR_MFFI __COS_LOGPAR_X4(M, F, F, I)
#define COS_LOGPAR_MFFD __COS_LOGPAR_X4(M, F, F, D)
#define COS_LOGPAR_MFFF __COS_LOGPAR_X4(M, F, F, F)
#define COS_LOGPAR_MFFS __COS_LOGPAR_X4(M, F, F, S)
#define COS_LOGPAR_MFFM __COS_LOGPAR_X4(M, F, F, M)
#define COS_LOGPAR_MFS __COS_LOGPAR_X3(M, F, S)
#define COS_LOGPAR_MFSI __COS_LOGPAR_X4(M, F, S, I)
#define COS_LOGPAR_MFSD __COS_LOGPAR_X4(M, F, S, D)
#define COS_LOGPAR_MFSF __COS_LOGPAR_X4(M, F, S, F)
#define COS_LOGPAR_MFSS __COS_LOGPAR_X4(M, F, S, S)
#define COS_LOGPAR_MFSM __COS_LOGPAR_X4(M, F, S, M)
#define COS_LOGPAR_MFM __COS_LOGPAR_X3(M, F, M)
#define COS_LOGPAR_MFMI __COS_LOGPAR_X4(M, F, M, I)
#define COS_LOGPAR_MFMD __COS_LOGPAR_X4(M, F, M, D)
#define COS_LOGPAR_MFMF __COS_LOGPAR_X4(M, F, M, F)
#define COS_LOGPAR_MFMS __COS_LOGPAR_X4(M, F, M, S)
#define COS_LOGPAR_MFMM __COS_LOGPAR_X4(M, F, M, M)
#define COS_LOGPAR_MS __COS_LOGPAR_X2(M, S)
#define COS_LOGPAR_MSI __COS_LOGPAR_X3(M, S, I)
#define COS_LOGPAR_MSII __COS_LOGPAR_X4(M, S, I, I)
#define COS_LOGPAR_MSID __COS_LOGPAR_X4(M, S, I, D)
#define COS_LOGPAR_MSIF __COS_LOGPAR_X4(M, S, I, F)
#define COS_LOGPAR_MSIS __COS_LOGPAR_X4(M, S, I, S)
#define COS_LOGPAR_MSIM __COS_LOGPAR_X4(M, S, I, M)
#define COS_LOGPAR_MSD __COS_LOGPAR_X3(M, S, D)
#define COS_LOGPAR_MSDI __COS_LOGPAR_X4(M, S, D, I)
#define COS_LOGPAR_MSDD __COS_LOGPAR_X4(M, S, D, D)
#define COS_LOGPAR_MSDF __COS_LOGPAR_X4(M, S, D, F)
#define COS_LOGPAR_MSDS __COS_LOGPAR_X4(M, S, D, S)
#define COS_LOGPAR_MSDM __COS_LOGPAR_X4(M, S, D, M)
#define COS_LOGPAR_MSF __COS_LOGPAR_X3(M, S, F)
#define COS_LOGPAR_MSFI __COS_LOGPAR_X4(M, S, F, I)
#define COS_LOGPAR_MSFD __COS_LOGPAR_X4(M, S, F, D)
#define COS_LOGPAR_MSFF __COS_LOGPAR_X4(M, S, F, F)
#define COS_LOGPAR_MSFS __COS_LOGPAR_X4(M, S, F, S)
#define COS_LOGPAR_MSFM __COS_LOGPAR_X4(M, S, F, M)
#define COS_LOGPAR_MSS __COS_LOGPAR_X3(M, S, S)
#define COS_LOGPAR_MSSI __COS_LOGPAR_X4(M, S, S, I)
#define COS_LOGPAR_MSSD __COS_LOGPAR_X4(M, S, S, D)
#define COS_LOGPAR_MSSF __COS_LOGPAR_X4(M, S, S, F)
#define COS_LOGPAR_MSSS __COS_LOGPAR_X4(M, S, S, S)
#define COS_LOGPAR_MSSM __COS_LOGPAR_X4(M, S, S, M)
#define COS_LOGPAR_MSM __COS_LOGPAR_X3(M, S, M)
#define COS_LOGPAR_MSMI __COS_LOGPAR_X4(M, S, M, I)
#define COS_LOGPAR_MSMD __COS_LOGPAR_X4(M, S, M, D)
#define COS_LOGPAR_MSMF __COS_LOGPAR_X4(M, S, M, F)
#define COS_LOGPAR_MSMS __COS_LOGPAR_X4(M, S, M, S)
#define COS_LOGPAR_MSMM __COS_LOGPAR_X4(M, S, M, M)
#define COS_LOGPAR_MM __COS_LOGPAR_X2(M, M)
#define COS_LOGPAR_MMI __COS_LOGPAR_X3(M, M, I)
#define COS_LOGPAR_MMII __COS_LOGPAR_X4(M, M, I, I)
#define COS_LOGPAR_MMID __COS_LOGPAR_X4(M, M, I, D)
#define COS_LOGPAR_MMIF __COS_LOGPAR_X4(M, M, I, F)
#define COS_LOGPAR_MMIS __COS_LOGPAR_X4(M, M, I, S)
#define COS_LOGPAR_MMIM __COS_LOGPAR_X4(M, M, I, M)
#define COS_LOGPAR_MMD __COS_LOGPAR_X3(M, M, D)
#define COS_LOGPAR_MMDI __COS_LOGPAR_X4(M, M, D, I)
#define COS_LOGPAR_MMDD __COS_LOGPAR_X4(M, M, D, D)
#define COS_LOGPAR_MMDF __COS_LOGPAR_X4(M, M, D, F)
#define COS_LOGPAR_MMDS __COS_LOGPAR_X4(M, M, D, S)
#define COS_LOGPAR_MMDM __COS_LOGPAR_X4(M, M, D, M)
#define COS_LOGPAR_MMF __COS_LOGPAR_X3(M, M, F)
#define COS_LOGPAR_MMFI __COS_LOGPAR_X4(M, M, F, I)
#define COS_LOGPAR_MMFD __COS_LOGPAR_X4(M, M, F, D)
#define COS_LOGPAR_MMFF __COS_LOGPAR_X4(M, M, F, F)
#define COS_LOGPAR_MMFS __COS_LOGPAR_X4(M, M, F, S)
#define COS_LOGPAR_MMFM __COS_LOGPAR_X4(M, M, F, M)
#define COS_LOGPAR_MMS __COS_LOGPAR_X3(M, M, S)
#define COS_LOGPAR_MMSI __COS_LOGPAR_X4(M, M, S, I)
#define COS_LOGPAR_MMSD __COS_LOGPAR_X4(M, M, S, D)
#define COS_LOGPAR_MMSF __COS_LOGPAR_X4(M, M, S, F)
#define COS_LOGPAR_MMSS __COS_LOGPAR_X4(M, M, S, S)
#define COS_LOGPAR_MMSM __COS_LOGPAR_X4(M, M, S, M)
#define COS_LOGPAR_MMM __COS_LOGPAR_X3(M, M, M)
#define COS_LOGPAR_MMMI __COS_LOGPAR_X4(M, M, M, I)
#define COS_LOGPAR_MMMD __COS_LOGPAR_X4(M, M, M, D)
#define COS_LOGPAR_MMMF __COS_LOGPAR_X4(M, M, M, F)
#define COS_LOGPAR_MMMS __COS_LOGPAR_X4(M, M, M, S)
#define COS_LOGPAR_MMMM __COS_LOGPAR_X4(M, M, M, M)

#endif
